// Auto-generated file containing pre-parsed tests data from the textbook.
const List<Map<String, String>> initialTestsData = [
  {
    'name': r"""’S’p’u’r’l’i’n’g’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Cervical spine""",
    'purpose': r"""’n’e’r’v’e’ ’r’o’o’t’ ’c’o’m’p’r’e’s’s’i’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’.’ ’E’x’t’e’n’d’ ’n’e’c’k’ ’a’n’d’ ’r’o’t’a’t’e’ ’h’e’a’d’.’ ’A’p’p’l’y’ ’d’o’w’n’w’a’r’d’ ’p’r’e’s’s’u’r’e’ ’t’o’ ’h’e’a’d’.’""",
    'positive_sign': r"""’r’a’d’i’a’t’i’n’g’ ’p’a’i’n’ ’i’n’t’o’ ’s’h’o’u’l’d’e’r’ ’o’r’ ’a’r’m’ ’o’n’ ’s’i’d’e’ ’t’o’ ’w’h’i’c’h’ ’t’h’e’ ’h’e’a’d’ ’i’s’ ’r’o’t’a’t’e’d’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’D’i’s’t’r’a’c’t’i’o’n’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Cervical spine""",
    'purpose': r"""’n’e’r’v’e’ ’r’o’o’t’ ’c’o’m’p’r’e’s’s’i’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’i’n’ ’s’i’t’t’i’n’g’.’ ’P’l’a’c’e’ ’o’n’e’ ’h’a’n’d’ ’u’n’d’e’r’ ’c’h’i’n’ ’a’n’d’ ’o’t’h’e’r’ ’h’a’n’d’ ’u’n’d’e’r’ ’o’c’c’i’p’u’t’.’ ’G’e’n’t’l’y’ ’l’i’f’t’ ’p’a’t’i’e’n’t’’’s’ ’h’e’a’d’.’""",
    'positive_sign': r"""’r’e’l’i’e’f’ ’ ’o’r’ ’d’e’c’r’e’a’s’e’ ’i’n’ ’p’a’i’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’c’t’i’v’e’ ’c’o’m’p’r’e’s’s’i’o’n’ ’t’e’s’t’ ’(’O’’’B’r’i’e’n’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’l’a’b’r’a’l’ ’p’a’t’h’o’l’o’g’y’ ’,’ ’a’c’r’o’m’i’o’c’l’a’v’i’c’u’l’a’r’ ’j’o’i’n’t’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’u’p’r’i’g’h’t’ ’w’i’t’h’ ’e’l’b’o’w’ ’i’n’ ’e’x’t’e’n’s’i’o’n’ ’a’n’d’ ’s’h’o’u’l’-’ ’d’e’r’ ’i’n’ ’9’0’°’ ’f’l’e’x’i’o’n’,’ ’1’0’-’1’5’°’ ’a’d’d’u’c’t’i’o’n’ ’a’n’d’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’.’ ’S’t’a’n’d’ ’b’e’h’i’n’d’ ’p’a’t’i’e’n’t’ ’a’n’d’ ’a’p’p’l’y’ ’d’o’w’n’w’a’r’d’ ’f’o’r’c’e’ ’t’o’ ’a’r’m’.’ ’R’e’p’e’a’t’ ’w’i’t’h’ ’a’r’m’ ’i’n’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’""",
    'positive_sign': r"""’p’a’i’n’/’i’n’c’r’e’a’s’e’d’ ’p’a’i’n’ ’w’i’t’h’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’ ’a’n’d’ ’d’e’c’r’e’a’s’e’d’ ’p’a’i’n’ ’w’i’t’h’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’ ’P’a’i’n’ ’i’n’s’i’d’e’ ’t’h’e’ ’g’l’e’n’o’-’ ’h’u’m’e’r’a’l’ ’j’o’i’n’t’ ’i’n’d’i’c’a’t’e’s’ ’l’a’b’r’a’l’ ’a’b’n’o’r’m’a’l’i’t’y’ ’.’ ’P’a’i’n’ ’o’v’e’r’ ’t’h’e’ ’a’c’r’o’m’i’o’c’l’a’v’i’c’u’l’a’r’ ’j’o’i’n’t’ ’i’n’d’i’c’a’t’e’s’ ’a’c’r’o’m’i’o’c’l’a’v’i’c’u’l’a’r’ ’j’o’i’n’t’ ’a’b’n’o’r’m’a’l’i’t’y’ ’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’n’t’e’r’i’o’r’ ’d’r’a’w’e’r’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’a’n’t’e’r’i’o’r’ ’s’h’o’u’l’d’e’r’ ’s’t’a’b’i’l’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’P’l’a’c’e’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’8’0’-’1’2’0’°’ ’a’b’d’u’c’-’ ’t’i’o’n’,’ ’0’-’2’0’°’ ’f’o’r’w’a’r’d’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’0’-’3’0’°’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’ ’S’t’a’b’i’l’i’z’e’ ’s’c’a’p’u’l’a’.’ ’D’r’a’w’ ’h’u’m’e’r’u’s’ ’a’n’t’e’r’i’o’r’l’y’ ’.’""",
    'positive_sign': r"""’c’l’i’c’k’ ’a’n’d’/’o’r’ ’a’p’p’r’e’h’e’n’s’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’n’t’e’r’i’o’r’ ’s’l’i’d’e’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’l’a’b’r’a’l’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’u’p’r’i’g’h’t’ ’w’i’t’h’ ’h’a’n’d’s’ ’o’n’ ’h’i’p’s’,’ ’t’h’u’m’b’s’ ’f’a’c’i’n’g’ ’p’o’s’t’e’r’i’o’r’l’y’ ’.’ ’S’t’a’n’d’ ’b’e’h’i’n’d’ ’p’a’t’i’e’n’t’ ’a’n’d’ ’s’t’a’b’i’l’i’z’e’ ’s’c’a’p’u’l’a’ ’a’n’d’ ’ ’c’l’a’v’i’c’l’e’ ’w’i’t’h’ ’o’n’e’ ’h’a’n’d’.’ ’W’i’t’h’ ’t’h’e’ ’o’t’h’e’r’,’ ’a’p’p’l’y’ ’a’n’ ’a’n’t’e’r’o’-’ ’s’u’p’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’e’l’b’o’w’ ’w’h’i’l’e’ ’i’n’s’t’r’u’c’t’i’n’g’ ’t’h’e’ ’p’a’t’i’e’n’t’ ’t’o’ ’g’e’n’t’l’y’ ’p’u’s’h’ ’b’a’c’k’ ’a’g’a’i’n’s’t’ ’t’h’e’ ’f’o’r’c’e’.’""",
    'positive_sign': r"""’p’a’i’n’/’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’/’c’l’i’c’k’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’p’p’r’e’h’e’n’s’i’o’n’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’g’l’e’n’o’h’u’m’e’r’a’l’ ’j’o’i’n’t’ ’s’t’a’b’i’l’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’i’n’ ’s’t’a’n’d’i’n’g’ ’o’r’ ’s’u’p’i’n’e’.’ ’A’b’d’u’c’t’ ’s’h’o’u’l’d’e’r’ ’t’o’ ’9’0’°’.’ ’M’o’v’e’ ’i’t’ ’i’n’t’o’ ’m’a’x’i’m’u’m’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’ ’I’f’ ’ ’m’o’v’e’m’e’n’t’ ’w’e’l’l’ ’t’o’l’e’r’a’t’e’d’,’ ’a’p’p’l’y’ ’a’ ’p’o’s’t’e’r’o’a’n’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’h’u’m’e’r’a’l’ ’h’e’a’d’.’""",
    'positive_sign': r"""’a’p’p’r’e’h’e’n’s’i’o’n’ ’a’n’d’ ’p’a’i’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’B’i’c’e’p’s’ ’l’o’a’d’ ’t’e’s’t’ ’I’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’s’u’p’e’r’i’o’r’ ’l’a’b’r’a’l’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’9’0’°’ ’a’b’d’u’c’t’i’o’n’,’ ’e’l’b’o’w’ ’i’n’ ’9’0’°’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’f’o’r’e’a’r’m’ ’s’u’p’i’n’a’t’e’d’.’ ’L’a’t’e’r’a’l’l’y’ ’r’o’t’a’t’e’ ’s’h’o’u’l’d’e’r’ ’u’n’t’i’l’ ’p’a’t’i’e’n’t’ ’b’e’c’o’m’e’s’ ’a’p’p’r’e’h’e’n’s’i’v’e’.’ ’M’a’i’n’t’a’i’n’ ’t’h’i’s’ ’p’o’s’i’t’i’o’n’.’ ’R’e’s’i’s’t’ ’e’l’b’o’w’ ’f’l’e’x’i’o’n’.’""",
    'positive_sign': r"""’p’a’i’n’/’a’p’p’r’e’h’e’n’s’i’o’n’ ’r’e’m’a’i’n’s’ ’u’n’c’h’a’n’g’e’d’ ’o’r’ ’i’n’c’r’e’a’s’e’s’ ’d’u’r’i’n’g’ ’r’e’s’i’s’t’e’d’ ’e’l’b’o’w’ ’f’l’e’x’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’B’i’c’e’p’s’ ’l’o’a’d’ ’t’e’s’t’ ’I’I’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’s’u’p’e’r’i’o’r’ ’l’a’b’r’a’l’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’1’2’0’°’ ’a’b’d’u’c’t’i’o’n’ ’a’n’d’ ’m’a’x’i’m’u’m’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’,’ ’e’l’b’o’w’ ’i’n’ ’9’0’°’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’f’o’r’e’a’r’m’ ’s’u’p’i’n’a’t’e’d’.’ ’R’e’s’i’s’t’ ’e’l’b’o’w’ ’f’l’e’x’i’o’n’.’""",
    'positive_sign': r"""’i’n’c’r’e’a’s’e’d’ ’p’a’i’n’ ’d’u’r’i’n’g’ ’r’e’s’i’s’t’e’d’ ’e’l’b’o’w’ ’f’l’e’x’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’C’l’u’n’k’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’t’e’a’r’ ’o’f’ ’ ’g’l’e’n’o’i’d’ ’l’a’b’r’u’m’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’A’b’d’u’c’t’ ’s’h’o’u’l’d’e’r’ ’o’v’e’r’ ’p’a’t’i’e’n’t’’’s’ ’h’e’a’d’.’ ’A’p’p’l’y’ ’a’n’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’p’o’s’t’e’r’i’o’r’ ’a’s’p’e’c’t’ ’o’f’ ’ ’h’u’m’e’r’a’l’ ’h’e’a’d’ ’w’h’i’l’e’ ’r’o’t’a’t’i’n’g’ ’h’u’m’e’r’u’s’ ’l’a’t’e’r’a’l’l’y’ ’.’""",
    'positive_sign': r"""’a’ ’c’l’u’n’k’ ’o’r’ ’g’r’i’n’d’i’n’g’ ’s’o’u’n’d’ ’a’n’d’/’o’r’ ’a’p’p’r’e’h’e’n’s’i’o’n’ ’i’f’ ’ ’a’n’t’e’r’i’o’r’ ’i’n’s’t’a’b’i’l’i’t’y’ ’p’r’e’s’e’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’C’r’a’n’k’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’l’a’b’r’a’l’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’ ’o’r’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’1’6’0’°’ ’f’l’e’x’i’o’n’ ’i’n’ ’s’c’a’p’u’l’a’r’ ’p’l’a’n’e’.’ ’H’o’l’d’ ’e’l’b’o’w’ ’a’n’d’ ’a’p’p’l’y’ ’a’ ’l’o’n’g’i’t’u’-’ ’d’i’n’a’l’ ’c’o’m’p’r’e’s’s’i’v’e’ ’f’o’r’c’e’ ’t’o’ ’h’u’m’e’r’u’s’ ’w’h’i’l’e’ ’r’o’t’a’t’i’n’g’ ’i’t’ ’m’e’d’i’-’ ’a’l’l’y’ ’a’n’d’ ’l’a’t’e’r’a’l’l’y’ ’.’ ’""",
    'positive_sign': r"""’p’a’i’n’/’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’,’ ’w’i’t’h’ ’o’r’ ’w’i’t’h’-’ ’o’u’t’ ’c’l’i’c’k’,’ ’u’s’u’a’l’l’y’ ’d’u’r’i’n’g’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’C’r’o’s’s’e’d’-’a’r’m’ ’a’d’d’u’c’t’i’o’n’ ’t’e’s’t’ ’(’A’p’l’e’y’ ’s’c’a’r’f’ ’t’e’s’t’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’a’c’r’o’m’i’o’c’l’a’v’i’c’u’l’a’r’ ’j’o’i’n’t’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’u’p’r’i’g’h’t’.’ ’H’o’r’i’z’o’n’t’a’l’l’y’ ’a’d’d’u’c’t’ ’t’h’e’ ’a’r’m’ ’a’s’ ’f’a’r’ ’a’s’ ’p’o’s’s’i’b’l’e’.’""",
    'positive_sign': r"""’p’a’i’n’ ’a’r’o’u’n’d’ ’a’c’r’o’m’i’o’c’l’a’v’i’c’u’l’a’r’ ’j’o’i’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’D’r’o’p’ ’t’e’s’t’ ’(’e’x’t’e’r’n’a’l’ ’r’o’t’a’t’i’o’n’ ’l’a’g’ ’s’i’g’n’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’i’n’f’r’a’s’p’i’n’a’t’u’s’ ’a’n’d’ ’s’u’p’r’a’s’p’i’n’a’t’u’s’ ’i’n’t’e’g’r’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’u’p’r’i’g’h’t’ ’w’i’t’h’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’2’0’°’ ’a’b’d’u’c’t’i’o’n’ ’(’i’n’ ’t’h’e’ ’s’c’a’p’u’l’a’r’ ’p’l’a’n’e’)’ ’w’i’t’h’ ’e’l’b’o’w’ ’i’n’ ’9’0’°’ ’f’l’e’x’i’o’n’.’ ’P’l’a’c’e’ ’s’h’o’u’l’-’ ’d’e’r’ ’i’n’ ’f’u’l’l’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’ ’S’u’p’p’o’r’t’ ’e’l’b’o’w’ ’a’n’d’ ’a’s’k’ ’p’a’t’i’e’n’t’ ’t’o’ ’h’o’l’d’ ’p’o’s’i’t’i’o’n’.’""",
    'positive_sign': r"""’a’r’m’ ’d’r’o’p’s’ ’i’n’t’o’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’H’a’w’k’i’n’s’-’K’e’n’n’e’d’y’ ’i’m’p’i’n’g’e’m’e’n’t’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’i’m’p’i’n’g’e’m’e’n’t’ ’o’f’ ’ ’s’u’p’r’a’s’p’i’n’a’t’u’s’ ’t’e’n’d’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’ ’o’r’ ’s’t’a’n’d’i’n’g’.’ ’F’o’r’w’a’r’d’ ’f’l’e’x’ ’s’h’o’u’l’-’ ’d’e’r’ ’t’o’ ’9’0’°’ ’a’n’d’ ’f’l’e’x’ ’e’l’b’o’w’ ’t’o’ ’9’0’°’.’ ’A’p’p’l’y’ ’p’a’s’s’i’v’e’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’H’o’r’n’b’l’o’w’e’r’’’s’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’t’e’r’e’s’ ’m’i’n’o’r’ ’i’n’t’e’g’r’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’ ’o’r’ ’s’t’a’n’d’i’n’g’ ’w’i’t’h’ ’a’r’m’s’ ’b’y’ ’s’i’d’e’.’ ’P’a’t’i’e’n’t’ ’l’i’f’t’s’ ’h’a’n’d’s’ ’u’p’ ’t’o’ ’m’o’u’t’h’.’""",
    'positive_sign': r"""’i’n’a’b’i’l’i’t’y’ ’t’o’ ’l’i’f’t’ ’t’h’e’ ’h’a’n’d’ ’t’o’ ’t’h’e’ ’m’o’u’t’h’ ’w’i’t’h’o’u’t’ ’a’b’d’u’c’t’i’n’g’ ’a’r’m’ ’f’i’r’s’t’ ’(’t’h’i’s’ ’c’o’m’p’e’n’s’a’t’o’r’y’ ’m’a’n’o’e’u’v’r’e’ ’o’n’ ’t’h’e’ ’a’f’f’e’c’t’e’d’ ’s’i’d’e’ ’i’s’ ’t’h’e’ ’h’o’r’n’b’l’o’w’e’r’’’s’ ’s’i’g’n’)’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’J’e’r’k’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’p’o’s’t’e’r’i’o’r’ ’s’h’o’u’l’d’e’r’ ’s’t’a’b’i’l’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’.’ ’P’l’a’c’e’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’9’0’°’ ’f’o’r’w’a’r’d’ ’f’l’e’x’-’ ’i’o’n’ ’a’n’d’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’.’ ’A’p’p’l’y’ ’l’o’n’g’i’t’u’d’i’n’a’l’ ’c’e’p’h’a’l’a’d’ ’f’o’r’c’e’ ’t’o’ ’h’u’m’e’r’u’s’ ’a’n’d’ ’m’o’v’e’ ’a’r’m’ ’i’n’t’o’ ’h’o’r’i’z’o’n’t’a’l’ ’a’d’d’u’c’t’i’o’n’.’""",
    'positive_sign': r"""’s’u’d’d’e’n’ ’j’e’r’k’ ’o’r’ ’c’l’u’n’k’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’i’f’t’-’o’f’f’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’s’u’b’s’c’a’p’u’l’a’r’i’s’ ’i’n’t’e’g’r’i’t’y’ ’.’ ’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’u’p’r’i’g’h’t’ ’w’i’t’h’ ’a’r’m’ ’m’e’d’i’a’l’l’y’ ’r’o’t’a’t’e’d’ ’b’e’h’i’n’d’ ’b’a’c’k’.’ ’P’a’t’i’e’n’t’ ’l’i’f’t’s’ ’h’a’n’d’ ’a’w’a’y’ ’f’r’o’m’ ’b’a’c’k’.’""",
    'positive_sign': r"""’i’n’a’b’i’l’i’t’y’ ’t’o’ ’l’i’f’t’ ’a’r’m’ ’i’n’d’i’c’a’t’e’s’ ’t’e’n’d’o’n’ ’r’u’p’t’u’r’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’o’a’d’ ’a’n’d’ ’s’h’i’f’t’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’a’n’t’e’r’i’o’r’ ’a’n’d’ ’p’o’s’t’e’r’i’o’r’ ’s’h’o’u’l’d’e’r’ ’s’t’a’b’i’l’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’.’ ’S’t’a’b’i’l’i’z’e’ ’s’c’a’p’u’l’a’ ’b’y’ ’f’i’x’i’n’g’ ’c’o’r’a’c’o’i’d’ ’p’r’o’c’e’s’s’ ’a’n’d’ ’s’p’i’n’e’ ’o’f’ ’ ’s’c’a’p’u’l’a’.’ ’G’r’a’s’p’ ’h’u’m’e’r’a’l’ ’h’e’a’d’ ’a’n’d’ ’a’p’p’l’y’ ’a’ ’m’e’d’i’a’l’,’ ’c’o’m’p’r’e’s’s’i’v’e’ ’f’o’r’c’e’ ’t’o’ ’s’e’a’t’ ’i’t’ ’i’n’ ’t’h’e’ ’g’l’e’n’o’i’d’ ’f’o’s’s’a’ ’(’l’o’a’d’)’.’ ’G’l’i’d’e’ ’t’h’e’ ’h’u’m’e’r’a’l’ ’h’e’a’d’ ’a’n’t’e’r’i’o’r’l’y’ ’a’n’d’ ’p’o’s’t’e’-’ ’r’i’o’r’l’y’ ’(’s’h’i’f’t’)’.’""",
    'positive_sign': r"""’i’n’c’r’e’a’s’e’d’ ’a’n’t’e’r’i’o’r’ ’o’r’ ’p’o’s’t’e’r’i’o’r’ ’g’l’i’d’e’ ’i’n’d’i’c’a’t’e’s’ ’a’n’t’e’r’i’o’r’ ’o’r’ ’p’o’s’t’e’r’i’o’r’ ’i’n’s’t’a’b’i’l’i’t’y’ ’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’N’e’e’r’ ’i’m’p’i’n’g’e’m’e’n’t’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’i’m’p’i’n’g’e’m’e’n’t’ ’o’f’ ’ ’s’u’p’r’a’s’p’i’n’a’t’u’s’ ’t’e’n’d’o’n’ ’a’n’d’/’o’r’ ’b’i’c’e’p’s’ ’t’e’n’d’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’ ’o’r’ ’s’t’a’n’d’i’n’g’.’ ’P’a’s’s’i’v’e’l’y’ ’e’l’e’v’a’t’e’ ’a’r’m’ ’t’h’r’o’u’g’h’ ’f’o’r’w’a’r’d’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’a’t’t’e’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’i’n’f’r’a’s’p’i’n’a’t’u’s’ ’a’n’d’ ’t’e’r’e’s’ ’m’i’n’o’r’ ’i’n’t’e’g’r’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’.’ ’P’l’a’c’e’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’9’0’°’ ’f’l’e’x’i’o’n’ ’i’n’ ’t’h’e’ ’s’c’a’p’u’l’a’r’ ’p’l’a’n’e’ ’a’n’d’ ’e’l’b’o’w’ ’i’n’ ’9’0’°’ ’f’l’e’x’i’o’n’.’ ’P’a’t’i’e’n’t’ ’r’o’t’a’t’e’s’ ’a’r’m’ ’l’a’t’e’r’a’l’l’y’ ’a’g’a’i’n’s’t’ ’r’e’s’i’s’t’a’n’c’e’.’""",
    'positive_sign': r"""’r’e’s’i’s’t’a’n’c’e’ ’w’i’t’h’ ’p’a’i’n’ ’i’n’d’i’c’a’t’e’s’ ’t’e’n’d’i’n’o’p’a’t’h’y’ ’.’ ’I’n’a’b’i’l’i’t’y’ ’t’o’ ’r’e’s’i’s’t’ ’w’i’t’h’ ’g’r’a’d’u’a’l’ ’l’o’w’e’r’i’n’g’ ’o’f’ ’ ’t’h’e’ ’a’r’m’ ’o’r’ ’f’o’r’e’-’ ’a’r’m’ ’i’n’d’i’c’a’t’e’s’ ’t’e’n’d’o’n’ ’r’u’p’t’u’r’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’o’s’t’e’r’i’o’r’ ’d’r’a’w’e’r’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’p’o’s’t’e’r’i’o’r’ ’s’h’o’u’l’d’e’r’ ’s’t’a’b’i’l’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’P’l’a’c’e’ ’s’h’o’u’l’d’e’r’ ’i’n’ ’1’0’0’-’1’2’0’°’ ’a’b’d’u’c’t’i’o’n’ ’a’n’d’ ’2’0’-’3’0’°’ ’f’o’r’w’a’r’d’ ’f’l’e’x’i’o’n’ ’w’i’t’h’ ’e’l’b’o’w’ ’f’l’e’x’e’d’ ’t’o’ ’1’2’0’°’.’ ’S’t’a’b’i’l’i’z’e’ ’s’c’a’p’u’l’a’.’ ’M’e’d’i’a’l’l’y’ ’r’o’t’a’t’e’ ’a’n’d’ ’f’o’r’w’a’r’d’ ’f’l’e’x’ ’s’h’o’u’l’d’e’r’ ’b’e’t’w’e’e’n’ ’6’0’°’ ’a’n’d’ ’8’0’°’ ’w’h’i’l’e’ ’p’u’s’h’i’n’g’ ’h’e’a’d’ ’o’f’ ’h’u’m’e’r’u’s’ ’p’o’s’t’e’r’i’o’r’l’y’ ’.’""",
    'positive_sign': r"""’s’i’g’n’i’f’i’c’a’n’t’ ’p’o’s’t’e’r’i’o’r’ ’d’i’s’p’l’a’c’e’m’e’n’t’ ’a’n’d’/’o’r’ ’p’a’t’i’e’n’t’ ’a’p’p’r’e’h’e’n’s’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’R’e’l’o’c’a’t’i’o’n’ ’t’e’s’t’ ’(’F’o’w’l’e’r’’’s’ ’s’i’g’n’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’d’i’f’f’e’r’e’n’t’i’a’t’e’s’ ’b’e’t’w’e’e’n’ ’a’n’t’e’r’i’o’r’ ’s’h’o’u’l’d’e’r’ ’s’t’a’b’i’l’i’t’y’ ’a’n’d’ ’p’r’i’m’a’r’y’ ’i’m’p’i’n’g’e’m’e’n’t’.’""",
    'procedure': r"""’p’e’r’f’o’r’m’ ’t’h’e’ ’a’p’p’r’e’h’e’n’s’i’o’n’ ’t’e’s’t’ ’i’n’ ’s’u’p’i’n’e’.’ ’A’t’ ’t’h’e’ ’p’o’i’n’t’ ’w’h’e’r’e’ ’t’h’e’ ’p’a’t’i’e’n’t’ ’f’e’e’l’s’ ’p’a’i’n’ ’o’r’ ’a’p’p’r’e’h’e’n’s’i’o’n’ ’a’p’p’l’y’ ’a’n’ ’a’n’t’e’r’o’p’o’s’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’h’u’m’e’r’a’l’ ’h’e’a’d’.’""",
    'positive_sign': r"""’p’e’r’s’i’s’t’e’n’c’e’ ’o’f’ ’ ’p’a’i’n’ ’o’r’ ’a’p’p’r’e’h’e’n’s’i’o’n’ ’i’n’d’i’c’a’t’e’s’ ’p’r’i’m’a’r’y’ ’i’m’p’i’n’g’e’m’e’n’t’.’ ’D’e’c’r’e’a’s’e’ ’i’n’ ’p’a’i’n’ ’o’r’ ’a’p’p’r’e’h’e’n’s’i’o’n’ ’a’n’d’ ’i’n’c’r’e’a’s’e’d’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’ ’i’n’d’i’c’a’t’e’s’ ’i’n’s’t’a’b’i’l’i’t’y’ ’a’n’d’ ’s’e’c’-’ ’o’n’d’a’r’y’ ’i’m’p’i’n’g’e’m’e’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’p’e’e’d’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’b’i’c’e’p’s’ ’t’e’n’d’o’n’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’ ’o’r’ ’s’t’a’n’d’i’n’g’.’ ’F’o’r’w’a’r’d’ ’f’l’e’x’ ’s’h’o’u’l’-’ ’d’e’r’,’ ’s’u’p’i’n’a’t’e’ ’f’o’r’e’a’r’m’ ’a’n’d’ ’e’x’t’e’n’d’ ’e’l’b’o’w’ ’.’ ’R’e’s’i’s’t’ ’p’a’t’i’e’n’t’’’s’ ’a’t’t’e’m’p’t’ ’t’o’ ’f’l’e’x’ ’s’h’o’u’l’d’e’r’.’""",
    'positive_sign': r"""’i’n’c’r’e’a’s’e’d’ ’p’a’i’n’ ’i’n’ ’b’i’c’i’p’i’t’a’l’ ’g’r’o’o’v’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’u’l’c’u’s’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’i’n’f’e’r’i’o’r’ ’s’h’o’u’l’d’e’r’ ’s’t’a’b’i’l’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’t’a’n’d’i’n’g’ ’o’r’ ’s’i’t’t’i’n’g’,’ ’a’r’m’ ’b’y’ ’s’i’d’e’.’ ’G’r’i’p’ ’a’r’m’ ’b’e’l’o’w’ ’e’l’b’o’w’ ’a’n’d’ ’p’u’l’l’ ’d’i’s’t’a’l’l’y’ ’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’ ’a’n’d’/’o’r’ ’a’p’p’e’a’r’a’n’c’e’ ’o’f’ ’ ’s’u’l’c’u’s’ ’u’n’d’e’r’ ’a’c’r’o’m’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’u’p’r’a’s’p’i’n’a’t’u’s’ ’(’e’m’p’t’y’ ’c’a’n’)’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’s’u’p’r’a’s’p’i’n’a’t’u’s’ ’t’e’n’d’o’n’ ’p’a’t’h’o’l’o’g’y’;’ ’s’u’p’r’a’s’c’a’p’u’l’a’r’ ’n’e’r’v’e’ ’n’e’u’r’o’p’a’t’h’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’ ’o’r’ ’s’t’a’n’d’i’n’g’.’ ’A’b’d’u’c’t’ ’s’h’o’u’l’d’e’r’ ’t’o’ ’9’0’°’.’ ’H’o’r’i’z’o’n’t’a’l’l’y’ ’f’l’e’x’ ’t’o’ ’3’0’°’ ’a’n’d’ ’m’e’d’i’a’l’l’y’ ’r’o’t’a’t’e’ ’s’o’ ’t’h’u’m’b’s’ ’p’o’i’n’t’ ’d’o’w’n’w’a’r’d’s’.’ ’R’e’s’i’s’t’ ’p’a’t’i’e’n’t’’’s’ ’a’t’t’e’m’p’t’ ’t’o’ ’a’b’d’u’c’t’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’ ’o’r’ ’w’e’a’k’n’e’s’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’Y’e’r’g’a’s’o’n’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""’b’i’c’e’p’s’ ’t’e’n’d’o’n’ ’p’a’t’h’o’l’o’g’y’;’ ’s’u’b’a’c’r’o’m’i’a’l’ ’i’m’p’i’n’g’e’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’ ’o’r’ ’s’t’a’n’d’i’n’g’ ’w’i’t’h’ ’e’l’b’o’w’ ’i’n’ ’9’0’°’ ’f’l’e’x’-’ ’i’o’n’ ’a’n’d’ ’f’o’r’e’a’r’m’ ’p’r’o’n’a’t’e’d’.’ ’R’e’s’i’s’t’ ’p’a’t’i’e’n’t’’’s’ ’a’t’t’e’m’p’t’s’ ’t’o’ ’s’u’p’i’n’a’t’e’.’""",
    'positive_sign': r"""’i’n’c’r’e’a’s’e’d’ ’p’a’i’n’ ’i’n’ ’b’i’c’i’p’i’t’a’l’ ’g’r’o’o’v’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’E’l’b’o’w’ ’f’l’e’x’i’o’n’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’c’u’b’i’t’a’l’ ’t’u’n’n’e’l’ ’(’u’l’n’a’r’ ’n’e’r’v’e’)’ ’s’y’n’d’r’o’m’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’t’a’n’d’i’n’g’ ’o’r’ ’s’i’t’t’i’n’g’.’ ’F’u’l’l’y’ ’f’l’e’x’ ’e’l’b’o’w’s’ ’w’i’t’h’ ’w’r’i’s’t’ ’e’x’t’e’n’d’e’d’.’ ’H’o’l’d’ ’f’o’r’ ’5’ ’m’i’n’u’t’e’s’.’""",
    'positive_sign': r"""’t’i’n’g’l’i’n’g’ ’o’r’ ’p’a’r’a’e’s’t’h’e’s’i’a’ ’i’n’ ’u’l’n’a’r’ ’n’e’r’v’e’ ’d’i’s’t’r’i’b’u’t’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’a’t’e’r’a’l’ ’e’p’i’c’o’n’d’y’l’i’t’i’s’ ’(’t’e’n’n’i’s’ ’e’l’b’o’w’)’ ’t’e’s’t’:’ ’m’e’t’h’o’d’ ’1’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’l’a’t’e’r’a’l’ ’e’p’i’c’o’n’d’y’l’i’t’i’s’.’""",
    'procedure': r"""’p’a’s’s’i’v’e’l’y’ ’e’x’t’e’n’d’ ’e’l’b’o’w’,’ ’p’r’o’n’a’t’e’ ’f’o’r’e’a’r’m’ ’a’n’d’ ’f’l’e’x’ ’w’r’i’s’t’ ’a’n’d’ ’f’i’n’g’e’r’s’ ’w’h’i’l’e’ ’p’a’l’p’a’t’i’n’g’ ’l’a’t’e’r’a’l’ ’e’p’i’c’o’n’d’y’l’e’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’a’t’e’r’a’l’ ’e’p’i’c’o’n’d’y’l’i’t’i’s’ ’(’t’e’n’n’i’s’ ’e’l’b’o’w’)’ ’t’e’s’t’:’ ’m’e’t’h’o’d’ ’2’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’l’a’t’e’r’a’l’ ’e’p’i’c’o’n’d’y’l’i’t’i’s’.’""",
    'procedure': r"""’r’e’s’i’s’t’ ’e’x’t’e’n’s’i’o’n’ ’o’f’ ’ ’m’i’d’d’l’e’ ’f’i’n’g’e’r’ ’d’i’s’t’a’l’ ’t’o’ ’P’I’P’ ’(’p’r’o’x’i’m’a’l’ ’i’n’t’e’r’p’h’a’l’a’n’g’e’a’l’)’ ’j’o’i’n’t’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’M’e’d’i’a’l’ ’e’p’i’c’o’n’d’y’l’i’t’i’s’ ’(’g’o’l’f’e’r’’’s’ ’e’l’b’o’w’)’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’m’e’d’i’a’l’ ’e’p’i’c’o’n’d’y’l’i’t’i’s’.’""",
    'procedure': r"""’p’a’s’s’i’v’e’l’y’ ’e’x’t’e’n’d’ ’e’l’b’o’w’,’ ’s’u’p’i’n’a’t’e’ ’f’o’r’e’a’r’m’ ’a’n’d’ ’e’x’t’e’n’d’ ’w’r’i’s’t’ ’a’n’d’ ’f’i’n’g’e’r’s’ ’w’h’i’l’e’ ’p’a’l’p’a’t’i’n’g’ ’m’e’d’i’a’l’ ’e’p’i’c’o’n’d’y’l’e’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’i’n’c’h’ ’g’r’i’p’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’a’n’t’e’r’i’o’r’ ’i’n’t’e’r’o’s’s’e’o’u’s’ ’(’m’e’d’i’a’n’)’ ’n’e’r’v’e’ ’e’n’t’r’a’p’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’p’i’n’c’h’e’s’ ’t’i’p’s’ ’o’f’ ’ ’i’n’d’e’x’ ’f’i’n’g’e’r’ ’a’n’d’ ’t’h’u’m’b’ ’t’o’g’e’t’h’e’r’.’""",
    'positive_sign': r"""’i’n’a’b’i’l’i’t’y’ ’t’o’ ’p’i’n’c’h’ ’t’i’p’ ’t’o’ ’t’i’p’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’T’i’n’e’l’’’s’ ’s’i’g’n’ ’(’a’t’ ’e’l’b’o’w’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’p’o’i’n’t’ ’o’f’ ’ ’r’e’g’e’n’e’r’a’t’i’o’n’ ’o’f’ ’ ’s’e’n’s’o’r’y’ ’f’i’b’r’e’s’ ’o’f’ ’ ’u’l’n’a’r’ ’n’e’r’v’e’.’""",
    'procedure': r"""’t’a’p’ ’u’l’n’a’r’ ’n’e’r’v’e’ ’i’n’ ’g’r’o’o’v’e’ ’b’e’t’w’e’e’n’ ’o’l’e’c’r’a’n’o’n’ ’a’n’d’ ’m’e’d’i’a’l’ ’e’p’i’c’o’n’d’y’l’e’.’""",
    'positive_sign': r"""’t’i’n’g’l’i’n’g’ ’s’e’n’s’a’t’i’o’n’ ’i’n’ ’u’l’n’a’r’ ’d’i’s’t’r’i’b’u’t’i’o’n’ ’o’f’ ’f’o’r’e’a’r’m’ ’a’n’d’ ’h’a’n’d’.’ ’F’u’r’t’h’e’s’t’ ’p’o’i’n’t’ ’a’t’ ’w’h’i’c’h’ ’a’b’n’o’r’m’a’l’ ’s’e’n’s’a’t’i’o’n’ ’f’e’l’t’ ’i’n’d’i’c’a’t’e’s’ ’p’o’i’n’t’ ’t’o’ ’w’h’i’c’h’ ’t’h’e’ ’n’e’r’v’e’ ’h’a’s’ ’r’e’g’e’n’e’r’a’t’e’d’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’V’a’l’g’u’s’ ’s’t’r’e’s’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’s’t’a’b’i’l’i’t’y’ ’o’f’ ’ ’m’e’d’i’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’i’n’ ’s’i’t’t’i’n’g’.’ ’S’t’a’b’i’l’i’z’e’ ’u’p’p’e’r’ ’a’r’m’ ’w’i’t’h’ ’e’l’b’o’w’ ’i’n’ ’2’0’-’3’0’°’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’h’u’m’e’r’u’s’ ’i’n’ ’f’u’l’l’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’ ’A’p’p’l’y’ ’a’b’d’u’c’t’i’o’n’/’v’a’l’g’u’s’ ’f’o’r’c’e’ ’t’o’ ’f’o’r’e’a’r’m’.’""",
    'positive_sign': r"""’i’n’c’r’e’a’s’e’d’ ’l’a’x’i’t’y’ ’o’r’ ’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’V’a’r’u’s’ ’s’t’r’e’s’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""’s’t’a’b’i’l’i’t’y’ ’o’f’ ’ ’l’a’t’e’r’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’i’n’ ’s’i’t’t’i’n’g’.’ ’S’t’a’b’i’l’i’z’e’ ’u’p’p’e’r’ ’a’r’m’ ’w’i’t’h’ ’e’l’b’o’w’ ’i’n’ ’2’0’-’3’0’°’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’h’u’m’e’r’u’s’ ’i’n’ ’f’u’l’l’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’.’ ’A’p’p’l’y’ ’a’d’d’u’c’t’i’o’n’/’v’a’r’u’s’ ’f’o’r’c’e’ ’t’o’ ’f’o’r’e’a’r’m’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’l’a’x’i’t’y’ ’o’r’ ’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’F’i’n’k’e’l’s’t’e’i’n’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’t’e’n’o’s’y’n’o’v’i’t’i’s’ ’o’f’ ’ ’a’b’d’u’c’t’o’r’ ’p’o’l’l’i’c’i’s’ ’l’o’n’g’u’s’ ’a’n’d’ ’e’x’t’e’n’s’o’r’ ’p’o’l’l’i’c’i’s’ ’b’r’e’v’i’s’ ’t’e’n’d’o’n’s’ ’(’d’e’ ’Q’u’e’r’v’a’i’n’’’s’ ’t’e’n’o’s’y’n’o’v’i’t’i’s’)’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’m’a’k’e’s’ ’a’ ’f’i’s’t’ ’w’i’t’h’ ’t’h’u’m’b’ ’i’n’s’i’d’e’.’ ’P’a’s’s’i’v’e’l’y’ ’m’o’v’e’ ’w’r’i’s’t’ ’i’n’t’o’ ’u’l’n’a’r’ ’d’e’v’i’a’t’i’o’n’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’F’r’o’m’e’n’t’’’s’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’u’l’n’a’r’ ’n’e’r’v’e’ ’p’a’r’a’l’y’s’i’s’.’""",
    'procedure': r"""’g’r’i’p’ ’p’i’e’c’e’ ’o’f’ ’ ’p’a’p’e’r’ ’b’e’t’w’e’e’n’ ’i’n’d’e’x’ ’f’i’n’g’e’r’ ’a’n’d’ ’t’h’u’m’b’.’ ’P’u’l’l’ ’p’a’p’e’r’ ’a’w’a’y’ ’.’""",
    'positive_sign': r"""’f’l’e’x’i’o’n’ ’o’f’ ’ ’I’P’ ’(’i’n’t’e’r’p’h’a’l’a’n’g’e’a’l’)’ ’t’h’u’m’b’ ’j’o’i’n’t’ ’a’s’ ’p’a’p’e’r’ ’p’u’l’l’e’d’ ’a’w’a’y’ ’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’i’g’a’m’e’n’t’o’u’s’ ’i’n’s’t’a’b’i’l’i’t’y’ ’t’e’s’t’ ’f’o’r’ ’t’h’e’ ’f’i’n’g’e’r’s’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’s’t’a’b’i’l’i’t’y’ ’o’f’ ’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’s’.’""",
    'procedure': r"""’a’p’p’l’y’ ’v’a’l’g’u’s’ ’a’n’d’ ’v’a’r’u’s’ ’f’o’r’c’e’ ’t’o’ ’P’I’P’ ’(’p’r’o’x’i’m’a’l’ ’i’n’t’e’r’p’h’a’l’a’n’g’e’a’l’)’ ’o’r’ ’D’I’P’ ’(’d’i’s’t’a’l’ ’i’n’t’e’r’p’h’a’l’a’n’g’e’a’l’)’ ’j’o’i’n’t’.’""",
    'positive_sign': r"""’i’n’c’r’e’a’s’e’d’ ’l’a’x’i’t’y’ ’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’i’n’b’u’r’g’’’s’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’t’e’n’d’o’n’ ’p’a’t’h’o’l’o’g’y’ ’a’t’ ’i’n’t’e’r’c’o’n’n’e’c’t’i’o’n’ ’b’e’t’w’e’e’n’ ’f’l’e’x’o’r’ ’p’o’l’l’i’c’i’s’ ’l’o’n’g’u’s’ ’a’n’d’ ’f’l’e’x’o’r’ ’i’n’d’i’c’i’s’.’""",
    'procedure': r"""’t’h’u’m’b’ ’f’l’e’x’i’o’n’ ’o’n’t’o’ ’h’y’p’o’t’h’e’n’a’r’ ’e’m’i’n’e’n’c’e’ ’a’n’d’ ’i’n’d’e’x’ ’f’i’n’g’e’r’ ’e’x’t’e’n’s’i’o’n’.’ ’""",
    'positive_sign': r"""’l’i’m’i’t’e’d’ ’e’x’t’e’n’s’i’o’n’ ’a’n’d’ ’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’u’n’o’t’r’i’q’u’e’t’r’a’l’ ’b’a’l’l’o’t’t’e’m’e’n’t’ ’(’R’e’a’g’a’n’’’s’)’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’s’t’a’b’i’l’i’t’y’ ’o’f’ ’ ’l’u’n’o’t’r’i’q’u’e’t’r’a’l’ ’l’i’g’a’m’e’n’t’.’""",
    'procedure': r"""’s’t’a’b’i’l’i’z’e’ ’l’u’n’a’t’e’ ’a’n’d’ ’a’p’p’l’y’ ’p’o’s’t’e’r’i’o’r’ ’a’n’d’ ’a’n’t’e’r’i’o’r’ ’g’l’i’d’e’ ’t’o’ ’t’r’i’q’u’e’t’r’u’m’ ’a’n’d’ ’p’i’s’i’f’o’r’m’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’,’ ’c’r’e’p’i’t’u’s’ ’o’r’ ’l’a’x’i’t’y’ ’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’h’a’l’e’n’’’s’ ’(’w’r’i’s’t’ ’f’l’e’x’i’o’n’)’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’m’e’d’i’a’n’ ’n’e’r’v’e’ ’p’a’t’h’o’l’o’g’y’;’ ’c’a’r’p’a’l’ ’t’u’n’n’e’l’ ’s’y’n’d’r’o’m’e’.’""",
    'procedure': r"""’p’l’a’c’e’ ’d’o’r’s’a’l’ ’a’s’p’e’c’t’ ’o’f’ ’ ’h’a’n’d’s’ ’t’o’g’e’t’h’e’r’ ’w’i’t’h’ ’w’r’i’s’t’s’ ’f’l’e’x’e’d’.’ ’H’o’l’d’ ’f’o’r’ ’1’ ’m’i’n’u’t’e’.’""",
    'positive_sign': r"""’t’i’n’g’l’i’n’g’ ’i’n’ ’d’i’s’t’r’i’b’u’t’i’o’n’ ’o’f’ ’ ’m’e’d’i’a’n’ ’n’e’r’v’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’R’e’v’e’r’s’e’ ’P’h’a’l’e’n’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’m’e’d’i’a’n’ ’n’e’r’v’e’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’l’a’c’e’ ’p’a’l’m’s’ ’o’f’ ’ ’h’a’n’d’s’ ’t’o’g’e’t’h’e’r’ ’w’i’t’h’ ’w’r’i’s’t’s’ ’e’x’t’e’n’d’e’d’.’ ’H’o’l’d’ ’f’o’r’ ’1’ ’m’i’n’u’t’e’.’""",
    'positive_sign': r"""’t’i’n’g’l’i’n’g’ ’i’n’ ’d’i’s’t’r’i’b’u’t’i’o’n’ ’o’f’ ’ ’m’e’d’i’a’n’ ’n’e’r’v’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’w’e’a’t’e’r’ ’f’i’n’g’e’r’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’r’u’p’t’u’r’e’ ’o’f’ ’ ’f’l’e’x’o’r’ ’d’i’g’i’t’o’r’u’m’ ’p’r’o’f’u’n’d’u’s’ ’t’e’n’d’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’m’a’k’e’s’ ’a’ ’f’i’s’t’.’""",
    'positive_sign': r"""’l’o’s’s’ ’o’f’ ’ ’D’I’P’ ’j’o’i’n’t’ ’f’l’e’x’i’o’n’ ’o’f’ ’ ’o’n’e’ ’o’f’ ’ ’t’h’e’ ’f’i’n’g’e’r’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’T’i’n’e’l’’’s’ ’s’i’g’n’ ’(’a’t’ ’t’h’e’ ’w’r’i’s’t’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’m’e’d’i’a’n’ ’n’e’r’v’e’ ’p’a’t’h’o’l’o’g’y’;’ ’c’a’r’p’a’l’ ’t’u’n’n’e’l’ ’s’y’n’d’r’o’m’e’.’""",
    'procedure': r"""’t’a’p’ ’o’v’e’r’ ’c’a’r’p’a’l’ ’t’u’n’n’e’l’.’""",
    'positive_sign': r"""’t’i’n’g’l’i’n’g’ ’o’r’ ’p’a’r’a’e’s’t’h’e’s’i’a’ ’i’n’ ’m’e’d’i’a’n’ ’d’i’s’t’r’i’b’u’t’i’o’n’ ’i’n’ ’h’a’n’d’.’ ’F’u’r’t’h’e’s’t’ ’p’o’i’n’t’ ’a’t’ ’w’h’i’c’h’ ’a’b’n’o’r’m’a’l’ ’s’e’n’s’a’t’i’o’n’ ’f’e’l’t’ ’i’n’d’i’c’a’t’e’s’ ’p’o’i’n’t’ ’t’o’ ’w’h’i’c’h’ ’t’h’e’ ’n’e’r’v’e’ ’h’a’s’ ’r’e’g’e’n’e’r’a’t’e’d’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’T’r’i’a’n’g’u’l’a’r’ ’f’i’b’r’o’c’a’r’t’i’l’a’g’e’ ’c’o’m’p’l’e’x’ ’(’T’F’C’C’)’ ’l’o’a’d’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’t’r’i’a’n’g’u’l’a’r’ ’f’i’b’r’o’c’a’r’t’i’l’a’g’e’ ’c’o’m’p’l’e’x’ ’i’n’t’e’g’r’i’t’y’ ’.’""",
    'procedure': r"""’h’o’l’d’ ’f’o’r’e’a’r’m’.’ ’W’i’t’h’ ’o’t’h’e’r’ ’h’a’n’d’ ’h’o’l’d’ ’w’r’i’s’t’ ’i’n’ ’u’l’n’a’r’ ’d’e’v’i’a’t’i’o’n’ ’t’h’e’n’ ’m’o’v’e’ ’i’t’ ’t’h’r’o’u’g’h’ ’s’u’p’i’n’a’t’i’o’n’ ’a’n’d’ ’p’r’o’n’a’t’i’o’n’ ’w’h’i’l’e’ ’a’p’p’l’y’i’n’g’ ’a’ ’c’o’m’p’r’e’s’s’i’v’e’ ’f’o’r’c’e’.’""",
    'positive_sign': r"""’p’a’i’n’,’ ’c’l’i’c’k’i’n’g’,’ ’c’r’e’p’i’t’u’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’W’a’t’s’o’n’ ’(’s’c’a’p’h’o’i’d’ ’s’h’i’f’t’)’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""’s’t’a’b’i’l’i’t’y’ ’o’f’ ’ ’s’c’a’p’h’o’i’d’.’ ’""",
    'procedure': r"""’h’o’l’d’ ’w’r’i’s’t’ ’i’n’ ’f’u’l’l’ ’u’l’n’a’r’ ’d’e’v’i’a’t’i’o’n’ ’a’n’d’ ’s’l’i’g’h’t’ ’e’x’t’e’n’-’ ’s’i’o’n’.’ ’W’i’t’h’ ’o’t’h’e’r’ ’h’a’n’d’ ’a’p’p’l’y’ ’p’r’e’s’s’u’r’e’ ’t’o’ ’s’c’a’p’h’o’i’d’ ’t’u’b’e’r’c’l’e’ ’(’p’a’l’m’a’r’ ’a’s’p’e’c’t’)’ ’a’n’d’ ’m’o’v’e’ ’w’r’i’s’t’ ’i’n’t’o’ ’r’a’d’i’a’l’ ’d’e’v’i’a’t’i’o’n’ ’a’n’d’ ’s’l’i’g’h’t’ ’f’l’e’x’i’o’n’.’""",
    'positive_sign': r"""’p’a’i’n’ ’a’n’d’/’o’r’ ’s’u’b’l’u’x’a’t’i’o’n’ ’o’f’ ’ ’s’c’a’p’h’o’i’d’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’C’o’m’p’r’e’s’s’i’o’n’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""’s’p’r’a’i’n’ ’o’f’ ’ ’p’o’s’t’e’r’i’o’r’ ’s’a’c’r’o’i’l’i’a’c’ ’j’o’i’n’t’ ’o’r’ ’l’i’g’a’m’e’n’t’s’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’o’r’ ’s’i’d’e’ ’l’y’i’n’g’.’ ’P’u’s’h’ ’r’i’g’h’t’ ’a’n’d’ ’l’e’f’t’ ’A’S’I’S’ ’(’a’n’t’e’r’i’o’r’ ’s’u’p’e’r’i’o’r’ ’i’l’i’a’c’ ’s’p’i’n’e’)’ ’t’o’w’a’r’d’s’ ’e’a’c’h’ ’o’t’h’e’r’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’G’a’p’p’i’n’g’ ’t’e’s’t’ ’(’d’i’s’t’r’a’c’t’i’o’n’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""’s’p’r’a’i’n’ ’o’f’ ’ ’a’n’t’e’r’i’o’r’ ’s’a’c’r’o’i’l’i’a’c’ ’j’o’i’n’t’ ’o’r’ ’l’i’g’a’m’e’n’t’s’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’P’u’s’h’ ’r’i’g’h’t’ ’a’n’d’ ’l’e’f’t’ ’A’S’I’S’ ’a’p’a’r’t’.’""",
    'positive_sign': r"""’r’e’p’r’o’d’u’c’t’i’o’n’ ’o’f’ ’ ’s’y’m’p’t’o’m’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’F’e’m’o’r’a’l’ ’s’h’e’a’r’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""’s’a’c’r’o’i’l’i’a’c’ ’j’o’i’n’t’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’a’n’d’ ’h’i’p’ ’i’n’ ’s’l’i’g’h’t’ ’f’l’e’x’i’o’n’,’ ’a’b’d’u’c’t’i’o’n’ ’a’n’d’ ’4’5’°’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’.’ ’A’p’p’l’y’ ’a’ ’g’r’a’d’e’d’ ’l’o’n’g’i’t’u’d’i’n’a’l’ ’c’e’p’h’a’l’a’d’ ’f’o’r’c’e’ ’a’l’o’n’g’ ’t’h’e’ ’f’e’m’o’r’a’l’ ’a’x’i’s’.’""",
    'positive_sign': r"""’p’a’i’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’G’i’l’l’e’t’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""’s’a’c’r’o’i’l’i’a’c’ ’j’o’i’n’t’ ’d’y’s’f’u’n’c’t’i’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’t’a’n’d’i’n’g’.’ ’P’a’l’p’a’t’e’ ’P’S’I’S’ ’(’p’o’s’t’e’r’i’o’r’ ’s’u’p’e’r’i’o’r’ ’i’l’i’a’c’ ’s’p’i’n’e’)’ ’a’n’d’ ’s’a’c’r’u’m’ ’a’t’ ’s’a’m’e’ ’l’e’v’e’l’.’ ’P’a’t’i’e’n’t’ ’f’l’e’x’e’s’ ’h’i’p’ ’a’n’d’ ’k’n’e’e’ ’o’n’ ’s’i’d’e’ ’b’e’i’n’g’ ’p’a’l’p’a’t’e’d’ ’w’h’i’l’e’ ’s’t’a’n’d’i’n’g’ ’o’n’ ’o’p’p’o’-’ ’s’i’t’e’ ’l’e’g’.’ ’R’e’p’e’a’t’ ’t’e’s’t’ ’o’n’ ’o’t’h’e’r’ ’s’i’d’e’ ’a’n’d’ ’c’o’m’p’a’r’e’.’""",
    'positive_sign': r"""’i’f’ ’ ’t’h’e’ ’P’S’I’S’ ’o’n’ ’t’h’e’ ’s’i’d’e’ ’t’e’s’t’e’d’ ’d’o’e’s’ ’n’o’t’ ’m’o’v’e’ ’d’o’w’n’w’a’r’d’s’ ’i’n’ ’r’e’l’a’t’i’o’n’ ’t’o’ ’t’h’e’ ’s’a’c’r’u’m’ ’i’t’ ’i’n’d’i’c’a’t’e’s’ ’h’y’p’o’m’o’-’ ’b’i’l’i’t’y’ ’o’n’ ’t’h’a’t’ ’s’i’d’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’i’e’d’a’l’l’u’’’s’ ’s’i’g’n’ ’(’s’i’t’t’i’n’g’ ’f’l’e’x’i’o’n’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""’m’o’v’e’m’e’n’t’ ’o’f’ ’ ’s’a’c’r’u’m’ ’o’n’ ’i’l’i’a’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’.’ ’L’e’f’t’ ’a’n’d’ ’r’i’g’h’t’ ’P’S’I’S’ ’a’r’e’ ’p’a’l’p’a’t’e’d’ ’w’h’i’l’e’ ’p’a’t’i’e’n’t’ ’f’o’r’w’a’r’d’ ’f’l’e’x’e’s’.’""",
    'positive_sign': r"""’o’n’e’ ’s’i’d’e’ ’m’o’v’e’s’ ’h’i’g’h’e’r’ ’t’h’a’n’ ’t’h’e’ ’o’t’h’e’r’,’ ’i’n’d’i’c’a’t’i’n’g’ ’h’y’p’o’m’o’b’i’l’i’t’y’ ’o’n’ ’t’h’a’t’ ’s’i’d’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’t’a’n’d’i’n’g’ ’f’l’e’x’i’o’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""’m’o’v’e’m’e’n’t’ ’o’f’ ’ ’i’l’i’a’ ’o’n’ ’s’a’c’r’u’m’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’t’a’n’d’i’n’g’.’ ’L’e’f’t’ ’a’n’d’ ’r’i’g’h’t’ ’P’S’I’S’ ’a’r’e’ ’p’a’l’p’a’t’e’d’ ’w’h’i’l’e’ ’p’a’t’i’e’n’t’ ’f’o’r’w’a’r’d’ ’f’l’e’x’e’s’.’""",
    'positive_sign': r"""’o’n’e’ ’s’i’d’e’ ’m’o’v’e’s’ ’h’i’g’h’e’r’ ’t’h’a’n’ ’t’h’e’ ’o’t’h’e’r’,’ ’i’n’d’i’c’a’t’i’n’g’ ’h’y’p’o’m’o’b’i’l’i’t’y’ ’o’n’ ’t’h’a’t’ ’s’i’d’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’u’p’i’n’e’ ’t’o’ ’s’i’t’ ’(’l’o’n’g’ ’s’i’t’t’i’n’g’)’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""’s’a’c’r’o’i’l’i’a’c’ ’j’o’i’n’t’ ’d’y’s’f’u’n’c’t’i’o’n’ ’c’a’u’s’e’d’ ’b’y’ ’p’e’l’v’i’c’ ’t’o’r’s’i’o’n’ ’o’r’ ’r’o’t’a’t’i’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’N’o’t’e’ ’l’e’v’e’l’ ’o’f’ ’ ’i’n’f’e’r’i’o’r’ ’b’o’r’d’e’r’s’ ’o’f’ ’m’e’d’i’a’l’ ’m’a’l’l’e’o’l’i’.’ ’P’a’t’i’e’n’t’ ’s’i’t’s’ ’u’p’ ’a’n’d’ ’r’e’l’a’t’i’v’e’ ’p’o’s’i’t’i’o’n’ ’o’f’ ’m’a’l’l’e’o’l’i’ ’n’o’t’e’d’.’""",
    'positive_sign': r"""’o’n’e’ ’l’e’g’ ’m’o’v’e’s’ ’u’p’ ’m’o’r’e’ ’t’h’a’n’ ’t’h’e’ ’o’t’h’e’r’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’F’a’b’e’r’’’s’ ’t’e’s’t’ ’(’P’a’t’r’i’c’k’’’s’ ’t’e’s’t’)’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’h’i’p’ ’j’o’i’n’t’ ’o’r’ ’s’a’c’r’o’i’l’i’a’c’ ’j’o’i’n’t’ ’d’y’s’f’u’n’c’t’i’o’n’;’ ’s’p’a’s’m’ ’o’f’ ’ ’i’l’i’o’-’ ’p’s’o’a’s’ ’m’u’s’c’l’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’P’l’a’c’e’ ’f’o’o’t’ ’o’f’ ’ ’t’e’s’t’ ’l’e’g’ ’o’n’ ’o’p’p’o’s’i’t’e’ ’k’n’e’e’.’ ’G’e’n’t’l’y’ ’l’o’w’e’r’ ’k’n’e’e’ ’o’f’ ’ ’t’e’s’t’ ’l’e’g’.’""",
    'positive_sign': r"""’k’n’e’e’ ’r’e’m’a’i’n’s’ ’a’b’o’v’e’ ’t’h’e’ ’o’p’p’o’s’i’t’e’ ’l’e’g’;’ ’p’a’i’n’ ’o’r’ ’s’p’a’s’m’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’e’g’ ’l’e’n’g’t’h’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’l’e’g’-’l’e’n’g’t’h’ ’d’i’s’c’r’e’p’a’n’c’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’M’e’a’s’u’r’e’ ’b’e’t’w’e’e’n’ ’t’h’e’ ’a’n’t’e’r’i’o’r’ ’s’u’p’e’r’i’o’r’ ’i’l’i’a’c’ ’s’p’i’n’e’ ’a’n’d’ ’t’h’e’ ’m’e’d’i’a’l’ ’o’r’ ’l’a’t’e’r’a’l’ ’m’a’l’l’e’o’l’u’s’.’""",
    'positive_sign': r"""’a’ ’d’i’f’f’e’r’e’n’c’e’ ’o’f’ ’ ’m’o’r’e’ ’t’h’a’n’ ’1’.’3’ ’ ’ ’ ’ ’ ’ ’c’m’ ’i’s’ ’c’o’n’s’i’d’e’r’e’d’ ’s’i’g’n’i’f’i’c’a’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’O’b’e’r’’’s’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’t’e’n’s’o’r’ ’f’a’s’c’i’a’ ’l’a’t’a’ ’a’n’d’ ’i’l’i’o’t’i’b’i’a’l’ ’b’a’n’d’ ’c’o’n’t’r’a’c’t’u’r’e’s’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’i’n’ ’s’i’d’e’ ’l’y’i’n’g’ ’w’i’t’h’ ’h’i’p’ ’a’n’d’ ’k’n’e’e’ ’o’f’ ’ ’l’o’w’e’r’ ’l’e’g’ ’f’l’e’x’e’d’.’ ’S’t’a’b’i’l’i’z’e’ ’p’e’l’v’i’s’.’ ’P’a’s’s’i’v’e’l’y’ ’a’b’d’u’c’t’ ’a’n’d’ ’e’x’t’e’n’d’ ’u’p’p’e’r’ ’l’e’g’ ’w’i’t’h’ ’k’n’e’e’ ’e’x’t’e’n’d’e’d’ ’o’r’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’,’ ’t’h’e’n’ ’a’l’l’o’w’ ’i’t’ ’t’o’ ’d’r’o’p’ ’t’o’w’a’r’d’s’ ’p’l’i’n’t’h’.’""",
    'positive_sign': r"""’u’p’p’e’r’ ’l’e’g’ ’r’e’m’a’i’n’s’ ’a’b’d’u’c’t’e’d’ ’a’n’d’ ’d’o’e’s’ ’n’o’t’ ’l’o’w’e’r’ ’t’o’ ’p’l’i’n’t’h’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’i’r’i’f’o’r’m’i’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’p’i’r’i’f’o’r’m’i’s’ ’i’n’v’o’l’v’e’m’e’n’t’ ’i’n’ ’s’c’i’a’t’i’c’ ’p’a’i’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’d’e’ ’l’y’i’n’g’ ’o’n’ ’e’d’g’e’ ’o’f’ ’ ’b’e’d’ ’w’i’t’h’ ’t’e’s’t’ ’l’e’g’ ’u’p’p’e’r’m’o’s’t’.’ ’F’l’e’x’ ’h’i’p’ ’t’o’ ’6’0’°’ ’w’i’t’h’ ’k’n’e’e’ ’f’l’e’x’e’d’.’ ’S’t’a’b’i’l’i’z’e’ ’h’i’p’ ’a’n’d’ ’a’p’p’l’y’ ’d’o’w’n’w’a’r’d’ ’p’r’e’s’s’u’r’e’ ’t’o’ ’k’n’e’e’.’""",
    'positive_sign': r"""’l’o’c’a’l’i’z’e’d’ ’p’a’i’n’ ’i’n’d’i’c’a’t’e’s’ ’t’i’g’h’t’ ’p’i’r’i’f’o’r’m’i’s’.’ ’P’a’i’n’ ’w’i’t’h’ ’r’a’d’i’a’t’i’o’n’ ’i’n’d’i’c’a’t’e’s’ ’s’c’i’a’t’i’c’ ’n’e’r’v’e’ ’i’n’v’o’l’v’e’m’e’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’Q’u’a’d’r’a’n’t’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’i’n’t’r’a’-’a’r’t’i’c’u’l’a’r’ ’h’i’p’ ’j’o’i’n’t’ ’p’a’t’h’o’l’o’g’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’P’l’a’c’e’ ’h’i’p’ ’i’n’ ’f’u’l’l’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’a’d’d’u’c’-’ ’t’i’o’n’.’ ’A’b’d’u’c’t’ ’h’i’p’ ’i’n’ ’a’ ’c’i’r’c’u’l’a’r’ ’a’r’c’,’ ’m’a’i’n’t’a’i’n’i’n’g’ ’f’u’l’l’ ’f’l’e’x’i’o’n’,’ ’w’h’i’l’e’ ’a’p’p’l’y’i’n’g’ ’a’ ’l’o’n’g’i’t’u’d’i’n’a’l’ ’c’o’m’p’r’e’s’s’i’v’e’ ’f’o’r’c’e’.’""",
    'positive_sign': r"""’p’a’i’n’,’ ’l’o’c’k’i’n’g’,’ ’c’r’e’p’i’t’u’s’,’ ’c’l’i’c’k’i’n’g’,’ ’a’p’p’r’e’h’e’n’s’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’R’e’c’t’u’s’ ’f’e’m’o’r’i’s’ ’c’o’n’t’r’a’c’t’u’r’e’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’r’e’c’t’u’s’ ’f’e’m’o’r’i’s’ ’c’o’n’t’r’a’c’t’u’r’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’t’e’s’t’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’ ’o’v’e’r’ ’e’d’g’e’ ’o’f’ ’ ’p’l’i’n’t’h’.’ ’P’a’t’i’e’n’t’ ’h’u’g’s’ ’o’t’h’e’r’ ’k’n’e’e’ ’t’o’ ’c’h’e’s’t’.’""",
    'positive_sign': r"""’k’n’e’e’ ’o’v’e’r’ ’e’d’g’e’ ’o’f’ ’ ’p’l’i’n’t’h’ ’e’x’t’e’n’d’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’T’h’o’m’a’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’h’i’p’ ’f’l’e’x’i’o’n’ ’c’o’n’t’r’a’c’t’u’r’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’P’a’t’i’e’n’t’ ’h’u’g’s’ ’o’n’e’ ’k’n’e’e’ ’t’o’ ’c’h’e’s’t’.’""",
    'positive_sign': r"""’o’p’p’o’s’i’t’e’ ’l’e’g’ ’l’i’f’t’s’ ’o’f’f’ ’ ’p’l’i’n’t’h’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’T’r’e’n’d’e’l’e’n’b’u’r’g’’’s’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’s’t’a’b’i’l’i’t’y’ ’o’f’ ’ ’t’h’e’ ’h’i’p’,’ ’s’t’r’e’n’g’t’h’ ’o’f’ ’ ’h’i’p’ ’a’b’d’u’c’t’o’r’s’ ’(’g’l’u’t’e’u’s’ ’m’e’d’i’u’s’)’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’t’a’n’d’s’ ’o’n’ ’o’n’e’ ’l’e’g’.’""",
    'positive_sign': r"""’p’e’l’v’i’s’ ’o’n’ ’o’p’p’o’s’i’t’e’ ’s’i’d’e’ ’d’r’o’p’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’W’e’b’e’r’-’B’a’r’s’t’o’w’ ’m’a’n’o’e’u’v’r’e’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""’l’e’g’ ’l’e’n’g’t’h’ ’a’s’y’m’m’e’t’r’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’h’i’p’s’ ’a’n’d’ ’k’n’e’e’s’ ’f’l’e’x’e’d’.’ ’H’o’l’d’ ’p’a’t’i’e’n’t’’’s’ ’f’e’e’t’,’ ’p’a’l’p’a’t’i’n’g’ ’m’e’d’i’a’l’ ’m’a’l’l’e’o’l’i’ ’w’i’t’h’ ’t’h’u’m’b’s’.’ ’P’a’t’i’e’n’t’ ’l’i’f’t’s’ ’p’e’l’v’i’s’ ’o’f’f’ ’ ’b’e’d’ ’a’n’d’ ’r’e’t’u’r’n’s’ ’t’o’ ’s’t’a’r’t’i’n’g’ ’p’o’s’i’t’i’o’n’.’ ’P’a’s’s’i’v’e’l’y’ ’e’x’t’e’n’d’ ’l’e’g’s’ ’a’n’d’ ’c’o’m’p’a’r’e’ ’r’e’l’a’t’i’v’e’ ’p’o’s’i’t’i’o’n’ ’o’f’ ’m’e’d’i’a’l’ ’m’a’l’l’e’o’l’i’.’""",
    'positive_sign': r"""’l’e’g’ ’l’e’n’g’t’h’ ’a’s’y’m’m’e’t’r’y’ ’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’b’d’u’c’t’i’o’n’ ’(’v’a’l’g’u’s’)’ ’s’t’r’e’s’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’f’u’l’l’ ’k’n’e’e’ ’e’x’t’e’n’s’i’o’n’:’ ’a’n’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’,’ ’m’e’d’i’a’l’ ’q’u’a’d’r’i’c’e’p’s’ ’e’x’p’a’n’s’i’o’n’,’ ’s’e’m’i’m’e’m’b’r’a’n’o’s’u’s’ ’m’u’s’c’l’e’,’ ’m’e’d’i’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’s’,’ ’p’o’s’t’e’r’i’o’r’ ’o’b’l’i’q’u’e’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’o’m’e’d’i’a’l’ ’c’a’p’s’u’l’e’.’ ’2’0’-’3’0’°’ ’f’l’e’x’i’o’n’:’ ’m’e’d’i’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’i’o’r’ ’o’b’l’i’q’u’e’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’o’m’e’d’i’a’l’ ’c’a’p’s’u’l’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’S’t’a’b’i’l’i’z’e’ ’a’n’k’l’e’ ’a’n’d’ ’a’p’p’l’y’ ’m’e’d’i’a’l’ ’p’r’e’s’s’u’r’e’ ’(’v’a’l’g’u’s’ ’s’t’r’e’s’s’)’ ’t’o’ ’k’n’e’e’ ’j’o’i’n’t’ ’a’t’ ’0’°’ ’a’n’d’ ’t’h’e’n’ ’a’t’ ’2’0’-’3’0’°’ ’e’x’t’e’n’s’i’o’n’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’ ’c’o’m’p’a’r’e’d’ ’w’i’t’h’ ’o’p’p’o’s’i’t’e’ ’k’n’e’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’d’d’u’c’t’i’o’n’ ’(’v’a’r’u’s’)’ ’s’t’r’e’s’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’f’u’l’l’ ’k’n’e’e’ ’e’x’t’e’n’s’i’o’n’:’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’s’,’ ’l’a’t’e’r’a’l’ ’g’a’s’-’ ’t’r’o’c’n’e’m’i’u’s’ ’m’u’s’c’l’e’,’ ’l’a’t’e’r’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’,’ ’a’r’c’u’a’t’e’-’ ’p’o’p’l’i’t’e’u’s’ ’c’o’m’p’l’e’x’,’ ’p’o’s’t’e’r’o’l’a’t’e’r’a’l’ ’c’a’p’s’u’l’e’,’ ’i’l’i’o’t’i’b’i’a’l’ ’b’a’n’d’,’ ’b’i’c’e’p’s’ ’f’e’m’o’r’i’s’ ’t’e’n’d’o’n’.’ ’2’0’-’3’0’°’ ’f’l’e’x’i’o’n’:’ ’l’a’t’e’r’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’,’ ’a’r’c’u’a’t’e’-’ ’p’o’p’l’i’t’e’u’s’ ’c’o’m’p’l’e’x’,’ ’p’o’s’t’e’r’o’l’a’t’e’r’a’l’ ’c’a’p’s’u’l’e’,’ ’i’l’i’o’t’i’b’i’a’l’ ’b’a’n’d’,’ ’b’i’c’e’p’s’ ’f’e’m’-’ ’o’r’i’s’ ’t’e’n’d’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’S’t’a’b’i’l’i’z’e’ ’a’n’k’l’e’.’ ’A’p’p’l’y’ ’l’a’t’e’r’a’l’ ’p’r’e’s’-’ ’s’u’r’e’ ’(’v’a’r’u’s’ ’s’t’r’e’s’s’)’ ’t’o’ ’k’n’e’e’ ’j’o’i’n’t’ ’a’t’ ’0’°’ ’a’n’d’ ’t’h’e’n’ ’a’t’ ’2’0’-’3’0’°’ ’e’x’t’e’n’s’i’o’n’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’ ’c’o’m’p’a’r’e’d’ ’t’o’ ’o’p’p’o’s’i’t’e’ ’k’n’e’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’n’t’e’r’i’o’r’ ’d’r’a’w’e’r’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’a’n’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’i’o’r’ ’o’b’l’i’q’u’e’ ’l’i’g’a’m’e’n’t’,’ ’a’r’c’u’a’t’e’-’p’o’p’l’i’t’e’u’s’ ’c’o’m’p’l’e’x’,’ ’p’o’s’t’e’r’o’m’e’d’i’a’l’ ’a’n’d’ ’p’o’s’t’e’r’o’l’a’-’ ’t’e’r’a’l’ ’c’a’p’s’u’l’e’s’,’ ’m’e’d’i’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’,’ ’i’l’i’o’t’i’b’i’a’l’ ’b’a’n’d’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’h’i’p’s’ ’f’l’e’x’e’d’ ’t’o’ ’4’5’°’ ’a’n’d’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’.’ ’S’t’a’b’i’l’i’z’e’ ’f’o’o’t’.’ ’A’p’p’l’y’ ’p’o’s’t’e’r’o’a’n’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’t’i’b’i’a’.’""",
    'positive_sign': r"""’t’i’b’i’a’ ’m’o’v’e’s’ ’m’o’r’e’ ’t’h’a’n’ ’6’ ’ ’ ’ ’ ’ ’ ’m’m’ ’o’n’ ’t’h’e’ ’f’e’m’u’r’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’p’l’e’y’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’d’i’s’t’r’a’c’t’i’o’n’ ’f’o’r’ ’l’i’g’a’m’e’n’t’o’u’s’ ’i’n’j’u’r’y’;’ ’c’o’m’p’r’e’s’s’i’o’n’ ’f’o’r’ ’m’e’n’i’s’c’u’s’ ’i’n’j’u’r’y’ ’.’ ’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’p’r’o’n’e’ ’w’i’t’h’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’.’ ’M’e’d’i’a’l’l’y’ ’a’n’d’ ’l’a’t’e’r’a’l’l’y’ ’r’o’t’a’t’e’ ’t’i’b’i’a’ ’-’ ’f’i’r’s’t’ ’w’i’t’h’ ’d’i’s’t’r’a’c’t’i’o’n’ ’a’n’d’ ’t’h’e’n’ ’c’o’m’p’r’e’s’s’i’o’n’.’""",
    'positive_sign': r"""’p’a’i’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’B’r’u’s’h’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’m’i’l’d’ ’e’f’f’u’s’i’o’n’.’""",
    'procedure': r"""’s’t’r’o’k’e’ ’m’e’d’i’a’l’ ’s’i’d’e’ ’o’f’ ’ ’p’a’t’e’l’l’a’ ’f’r’o’m’ ’j’u’s’t’ ’b’e’l’o’w’ ’j’o’i’n’t’ ’l’i’n’e’ ’u’p’ ’t’o’ ’s’u’p’r’a’p’a’t’e’l’l’a’r’ ’p’o’u’c’h’ ’t’w’o’ ’o’r’ ’t’h’r’e’e’ ’t’i’m’e’s’.’ ’U’s’e’ ’o’p’p’o’s’i’t’e’ ’h’a’n’d’ ’t’o’ ’s’t’r’o’k’e’ ’d’o’w’n’ ’l’a’t’e’r’a’l’ ’s’i’d’e’ ’o’f’ ’ ’p’a’t’e’l’l’a’.’""",
    'positive_sign': r"""’f’l’u’i’d’ ’t’r’a’v’e’l’s’ ’t’o’ ’m’e’d’i’a’l’ ’s’i’d’e’ ’a’n’d’ ’a’p’p’e’a’r’s’ ’a’s’ ’b’u’l’g’e’ ’b’e’l’o’w’ ’d’i’s’t’a’l’ ’b’o’r’d’e’r’ ’o’f’ ’ ’p’a’t’e’l’l’a’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’E’x’t’e’r’n’a’l’ ’r’o’t’a’t’i’o’n’ ’r’e’c’u’r’v’a’t’u’m’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’p’o’s’t’e’r’o’l’a’t’e’r’a’l’ ’r’o’t’a’r’y’ ’s’t’a’b’i’l’i’t’y’ ’i’n’ ’k’n’e’e’ ’e’x’t’e’n’s’i’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’H’o’l’d’ ’h’e’e’l’ ’a’n’d’ ’p’l’a’c’e’ ’k’n’e’e’ ’i’n’ ’3’0’°’ ’f’l’e’x’i’o’n’.’ ’S’l’o’w’l’y’ ’e’x’t’e’n’d’ ’k’n’e’e’ ’w’h’i’l’e’ ’p’a’l’p’a’t’i’n’g’ ’p’o’s’t’e’r’o’l’a’t’e’r’a’l’ ’a’s’p’e’c’t’ ’o’f’ ’ ’k’n’e’e’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’h’y’p’e’r’e’x’t’e’n’s’i’o’n’ ’a’n’d’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’ ’p’a’l’p’a’t’e’d’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’F’a’i’r’b’a’n’k’s’ ’’’ ’a’p’p’r’e’h’e’n’s’i’o’n’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’p’a’t’e’l’l’a’r’ ’s’u’b’l’u’x’a’t’i’o’n’ ’o’r’ ’d’i’s’l’o’c’a’t’i’o’n’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’k’n’e’e’ ’i’n’ ’3’0’°’ ’f’l’e’x’i’o’n’ ’a’n’d’ ’q’u’a’d’s’ ’r’e’l’a’x’e’d’.’ ’P’a’s’s’i’v’e’l’y’ ’g’l’i’d’e’ ’p’a’t’e’l’l’a’ ’l’a’t’e’r’a’l’l’y’ ’.’""",
    'positive_sign': r"""’p’a’t’i’e’n’t’ ’a’p’p’r’e’h’e’n’s’i’o’n’ ’o’r’ ’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’H’u’g’h’s’t’o’n’ ’p’l’i’c’a’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’i’n’f’l’a’m’m’a’t’i’o’n’ ’o’f’ ’ ’s’u’p’r’a’p’a’t’e’l’l’a’r’ ’p’l’i’c’a’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’F’l’e’x’ ’a’n’d’ ’m’e’d’i’a’l’l’y’ ’r’o’t’a’t’e’ ’k’n’e’e’ ’w’h’i’l’e’ ’a’p’p’l’y’i’n’g’ ’m’e’d’i’a’l’ ’g’l’i’d’e’ ’t’o’ ’p’a’t’e’l’l’a’ ’a’n’d’ ’p’a’l’p’a’t’i’n’g’ ’m’e’d’i’a’l’ ’f’e’m’-’ ’o’r’a’l’ ’c’o’n’d’y’l’e’.’ ’P’a’s’s’i’v’e’l’y’ ’e’x’t’e’n’d’ ’a’n’d’ ’f’l’e’x’ ’k’n’e’e’.’""",
    'positive_sign': r"""’p’o’p’p’i’n’g’ ’o’f’ ’ ’p’l’i’c’a’ ’b’a’n’d’ ’o’v’e’r’ ’f’e’m’o’r’a’l’ ’c’o’n’d’y’l’e’,’ ’t’e’n’d’e’r’n’e’s’s’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’L’a’c’h’m’a’n’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’a’n’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’i’o’r’ ’o’b’l’i’q’u’e’ ’l’i’g’a’m’e’n’t’,’ ’a’r’c’u’a’t’e’-’p’o’p’l’i’t’e’u’s’ ’c’o’m’p’l’e’x’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’0’-’3’0’°’.’ ’S’t’a’b’i’l’i’z’e’ ’f’e’m’u’r’.’ ’A’p’p’l’y’ ’p’o’s’t’e’r’o’a’n’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’t’i’b’i’a’.’""",
    'positive_sign': r"""’s’o’f’t’ ’e’n’d’ ’f’e’e’l’ ’o’r’ ’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’M’c’C’o’n’n’e’l’l’ ’t’e’s’t’ ’f’o’r’ ’c’h’o’n’d’r’o’m’a’l’a’c’i’a’ ’p’a’t’e’l’l’a’e’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’c’h’o’n’d’r’o’m’a’l’a’c’i’a’ ’p’a’t’e’l’l’a’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’i’n’ ’h’i’g’h’ ’s’i’t’t’i’n’g’ ’w’i’t’h’ ’f’e’m’u’r’ ’l’a’t’e’r’a’l’l’y’ ’r’o’t’a’t’e’d’.’ ’I’s’o’m’e’t’r’i’c’ ’q’u’a’d’ ’c’o’n’t’r’a’c’t’i’o’n’s’ ’a’r’e’ ’p’e’r’f’o’r’m’e’d’ ’a’t’ ’0’°’,’ ’3’0’°’,’ ’6’0’°’,’ ’9’0’°’ ’a’n’d’ ’1’2’0’°’ ’o’f’ ’ ’k’n’e’e’ ’f’l’e’x’i’o’n’ ’f’o’r’ ’1’0’ ’s’e’c’o’n’d’s’.’ ’I’f’ ’ ’p’a’i’n’ ’i’s’ ’p’r’o’d’u’c’e’d’ ’w’i’t’h’ ’a’n’y’ ’o’f’ ’ ’t’h’e’s’e’ ’m’o’v’e’m’e’n’t’s’,’ ’r’e’p’e’a’t’ ’t’e’s’t’ ’w’i’t’h’ ’p’a’t’e’l’l’a’ ’p’u’s’h’e’d’ ’m’e’d’i’a’l’l’y’ ’.’""",
    'positive_sign': r"""’d’e’c’r’e’a’s’e’ ’i’n’ ’s’y’m’p’t’o’m’s’ ’w’i’t’h’ ’m’e’d’i’a’l’ ’g’l’i’d’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’M’c’M’u’r’r’a’y’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’m’e’d’i’a’l’ ’m’e’n’i’s’c’u’s’ ’a’n’d’ ’l’a’t’e’r’a’l’ ’m’e’n’i’s’c’u’s’ ’i’n’j’u’r’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’t’e’s’t’ ’k’n’e’e’ ’c’o’m’p’l’e’t’e’l’y’ ’f’l’e’x’e’d’.’ ’T’o’ ’t’e’s’t’ ’t’h’e’ ’m’e’d’i’a’l’ ’m’e’n’i’s’c’u’s’,’ ’l’a’t’e’r’a’l’l’y’ ’r’o’t’a’t’e’ ’k’n’e’e’ ’a’n’d’ ’p’a’s’s’i’v’e’l’y’ ’e’x’t’e’n’d’ ’t’o’ ’9’0’°’ ’w’h’i’l’e’ ’p’a’l’p’a’t’i’n’g’ ’j’o’i’n’t’ ’l’i’n’e’.’ ’T’o’ ’t’e’s’t’ ’t’h’e’ ’l’a’t’e’r’a’l’ ’m’e’n’i’s’c’u’s’,’ ’r’e’p’e’a’t’ ’t’e’s’t’ ’w’i’t’h’ ’t’h’e’ ’k’n’e’e’ ’i’n’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’.’""",
    'positive_sign': r"""’a’ ’s’n’a’p’ ’o’r’ ’c’l’i’c’k’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’o’s’t’e’r’i’o’r’ ’d’r’a’w’e’r’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’p’o’s’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’,’ ’a’r’c’u’a’t’e’-’p’o’p’l’i’t’e’u’s’ ’c’o’m’p’l’e’x’,’ ’p’o’s’t’e’r’i’o’r’ ’o’b’l’i’q’u’e’ ’l’i’g’a’m’e’n’t’,’ ’a’n’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’h’i’p’s’ ’f’l’e’x’e’d’ ’t’o’ ’4’5’°’ ’a’n’d’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’.’ ’S’t’a’b’i’l’i’z’e’ ’f’o’o’t’.’ ’A’p’p’l’y’ ’a’n’t’e’r’o’p’o’s’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’t’i’b’i’a’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’o’s’t’e’r’i’o’r’ ’s’a’g’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’p’o’s’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’,’ ’a’r’c’u’a’t’e’-’p’o’p’l’i’t’e’u’s’ ’c’o’m’p’l’e’x’,’ ’p’o’s’t’e’r’i’o’r’ ’o’b’l’i’q’u’e’ ’l’i’g’a’m’e’n’t’,’ ’a’n’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’h’i’p’s’ ’f’l’e’x’e’d’ ’t’o’ ’4’5’°’ ’a’n’d’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’ ’w’i’t’h’ ’f’e’e’t’ ’o’n’ ’p’l’i’n’t’h’.’""",
    'positive_sign': r"""’t’i’b’i’a’ ’d’r’o’p’s’ ’p’o’s’t’e’r’i’o’r’l’y’ ’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’l’o’c’u’m’ ’t’e’s’t’ ’f’o’r’ ’a’n’t’e’r’o’l’a’t’e’r’a’l’ ’r’o’t’a’r’y’ ’i’n’s’t’a’b’i’l’i’t’y’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’a’n’t’e’r’i’o’r’ ’a’n’d’ ’p’o’s’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’s’,’ ’p’o’s’t’e’r’o’l’a’-’ ’t’e’r’a’l’ ’c’a’p’s’u’l’e’,’ ’a’r’c’u’a’t’e’-’p’o’p’l’i’t’e’u’s’ ’c’o’m’p’l’e’x’,’ ’l’a’t’e’r’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’s’,’ ’i’l’i’o’t’i’b’i’a’l’ ’b’a’n’d’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’h’i’p’s’ ’f’l’e’x’e’d’ ’t’o’ ’4’5’°’ ’a’n’d’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’.’ ’P’l’a’c’e’ ’f’o’o’t’ ’i’n’ ’3’0’°’ ’m’e’d’i’a’l’ ’r’o’t’a’t’i’o’n’ ’a’n’d’ ’s’t’a’b’i’-’ ’l’i’z’e’.’ ’A’p’p’l’y’ ’p’o’s’t’e’r’o’a’n’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’t’i’b’i’a’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’ ’o’n’ ’l’a’t’e’r’a’l’ ’s’i’d’e’ ’w’h’e’n’ ’c’o’m’-’ ’p’a’r’e’d’ ’w’i’t’h’ ’o’t’h’e’r’ ’k’n’e’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’S’l’o’c’u’m’ ’t’e’s’t’ ’f’o’r’ ’a’n’t’e’r’o’m’e’d’i’a’l’ ’r’o’t’a’r’y’ ’i’n’s’t’a’b’i’l’i’t’y’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""’m’e’d’i’a’l’ ’c’o’l’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’i’o’r’ ’o’b’l’i’q’u’e’ ’l’i’g’a’m’e’n’t’,’ ’p’o’s’t’e’r’o’m’e’d’i’a’l’ ’c’a’p’s’u’l’e’,’ ’a’n’t’e’r’i’o’r’ ’c’r’u’c’i’a’t’e’ ’l’i’g’a’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’ ’w’i’t’h’ ’h’i’p’s’ ’f’l’e’x’e’d’ ’t’o’ ’4’5’°’ ’a’n’d’ ’k’n’e’e’ ’f’l’e’x’e’d’ ’t’o’ ’9’0’°’.’ ’P’l’a’c’e’ ’f’o’o’t’ ’i’n’ ’1’5’°’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’ ’a’n’d’ ’s’t’a’b’i’-’ ’l’i’z’e’.’ ’A’p’p’l’y’ ’p’o’s’t’e’r’o’a’n’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’t’i’b’i’a’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’ ’o’n’ ’m’e’d’i’a’l’ ’s’i’d’e’ ’w’h’e’n’ ’c’o’m’-’ ’p’a’r’e’d’ ’w’i’t’h’ ’o’t’h’e’r’ ’k’n’e’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’n’t’e’r’i’o’r’ ’d’r’a’w’e’r’ ’s’i’g’n’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Ankle and foot""",
    'purpose': r"""’m’e’d’i’a’l’ ’a’n’d’ ’l’a’t’e’r’a’l’ ’l’i’g’a’m’e’n’t’ ’i’n’t’e’g’r’i’t’y’ ’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’p’r’o’n’e’ ’w’i’t’h’ ’k’n’e’e’ ’f’l’e’x’e’d’.’ ’A’p’p’l’y’ ’p’o’s’t’e’r’o’-’ ’a’n’t’e’r’i’o’r’ ’f’o’r’c’e’ ’t’o’ ’t’a’l’u’s’ ’w’i’t’h’ ’a’n’k’l’e’ ’i’n’ ’d’o’r’s’i’f’l’e’x’i’o’n’ ’a’n’d’ ’t’h’e’n’ ’p’l’a’n’t’a’r’f’l’e’x’i’o’n’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’a’n’t’e’r’i’o’r’ ’m’o’v’e’m’e’n’t’ ’(’b’o’t’h’ ’l’i’g’a’m’e’n’t’s’ ’a’f’f’e’c’t’e’d’)’ ’o’r’ ’m’o’v’e’m’e’n’t’ ’o’n’ ’o’n’e’ ’s’i’d’e’ ’o’n’l’y’ ’(’l’i’g’a’m’e’n’t’ ’o’n’ ’t’h’a’t’ ’s’i’d’e’ ’a’f’f’e’c’t’e’d’)’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’T’a’l’a’r’ ’t’i’l’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Ankle and foot""",
    'purpose': r"""’a’d’d’u’c’t’i’o’n’:’ ’m’a’i’n’l’y’ ’i’n’t’e’g’r’i’t’y’ ’o’f’ ’ ’c’a’l’c’a’n’e’o’f’i’b’u’l’a’r’ ’l’i’g’a’-’ ’m’e’n’t’ ’b’u’t’ ’a’l’s’o’ ’a’n’t’e’r’i’o’r’ ’t’a’l’o’f’i’b’u’l’a’r’ ’l’i’g’a’m’e’n’t’.’ ’A’b’d’u’c’t’i’o’n’:’ ’i’n’t’e’g’r’i’t’y’ ’o’f’ ’ ’d’e’l’t’o’i’d’ ’l’i’g’a’m’e’n’t’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’p’r’o’n’e’,’ ’s’u’p’i’n’e’ ’o’r’ ’s’i’d’e’ ’l’y’i’n’g’ ’w’i’t’h’ ’k’n’e’e’ ’f’l’e’x’e’d’.’ ’T’i’l’t’ ’t’a’l’u’s’ ’i’n’t’o’ ’a’b’d’u’c’t’i’o’n’ ’a’n’d’ ’a’d’d’u’c’t’i’o’n’ ’w’i’t’h’ ’p’a’t’i’e’n’t’’’s’ ’f’o’o’t’ ’i’n’ ’n’e’u’t’r’a’l’.’""",
    'positive_sign': r"""’e’x’c’e’s’s’i’v’e’ ’m’o’v’e’m’e’n’t’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’T’h’o’m’p’s’o’n’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Ankle and foot""",
    'purpose': r"""’A’c’h’i’l’l’e’s’ ’t’e’n’d’o’n’ ’r’u’p’t’u’r’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’p’r’o’n’e’ ’w’i’t’h’ ’f’e’e’t’ ’o’v’e’r’ ’e’d’g’e’ ’o’f’ ’ ’p’l’i’n’t’h’.’ ’S’q’u’e’e’z’e’ ’c’a’l’f’ ’ ’m’u’s’c’l’e’s’.’""",
    'positive_sign': r"""’a’b’s’e’n’c’e’ ’o’f’ ’ ’p’l’a’n’t’a’r’f’l’e’x’i’o’n’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’A’d’s’o’n’’’s’ ’m’a’n’o’e’u’v’r’e’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Common vascular tests""",
    'purpose': r"""’t’h’o’r’a’c’i’c’ ’o’u’t’l’e’t’ ’s’y’n’d’r’o’m’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’i’t’t’i’n’g’.’ ’P’a’t’i’e’n’t’ ’t’u’r’n’s’ ’h’e’a’d’ ’t’o’w’a’r’d’s’ ’t’e’s’t’ ’a’r’m’ ’a’n’d’ ’e’x’t’e’n’d’s’ ’h’e’a’d’.’ ’L’a’t’e’r’a’l’l’y’ ’r’o’t’a’t’e’ ’a’n’d’ ’e’x’t’e’n’d’ ’ ’s’h’o’u’l’d’e’r’ ’ ’a’n’d’ ’a’r’m’ ’w’h’i’l’e’ ’p’a’l’p’a’t’i’n’g’ ’r’a’d’i’a’l’ ’p’u’l’s’e’.’ ’P’a’t’i’e’n’t’ ’t’a’k’e’s’ ’a’ ’d’e’e’p’ ’b’r’e’a’t’h’ ’a’n’d’ ’h’o’l’d’s’ ’i’t’.’""",
    'positive_sign': r"""’d’i’s’a’p’p’e’a’r’a’n’c’e’ ’o’f’ ’ ’r’a’d’i’a’l’ ’p’u’l’s’e’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’H’o’m’a’n’’’s’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Common vascular tests""",
    'purpose': r"""’d’e’e’p’ ’v’e’i’n’ ’t’h’r’o’m’b’o’p’h’l’e’b’i’t’i’s’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’u’p’i’n’e’.’ ’P’a’s’s’i’v’e’ ’d’o’r’s’i’f’l’e’x’i’o’n’ ’o’f’ ’ ’a’n’k’l’e’ ’w’i’t’h’ ’k’n’e’e’ ’e’x’t’e’n’d’e’d’.’""",
    'positive_sign': r"""’p’a’i’n’ ’i’n’ ’t’h’e’ ’c’a’l’f’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""’P’r’o’v’o’c’a’t’i’o’n’ ’e’l’e’v’a’t’i’o’n’ ’t’e’s’t’""",
    'category': r"""Musculoskeletal""",
    'region': r"""Common vascular tests""",
    'purpose': r"""’t’h’o’r’a’c’i’c’ ’o’u’t’l’e’t’ ’s’y’n’d’r’o’m’e’.’""",
    'procedure': r"""’p’a’t’i’e’n’t’ ’s’t’a’n’d’i’n’g’ ’w’i’t’h’ ’a’r’m’s’ ’a’b’o’v’e’ ’h’e’a’d’.’ ’O’p’e’n’s’ ’a’n’d’ ’c’l’o’s’e’s’ ’h’a’n’d’s’ ’1’5’ ’t’i’m’e’s’.’""",
    'positive_sign': r"""’f’a’t’i’g’u’e’,’ ’c’r’a’m’p’,’ ’t’i’n’g’l’i’n’g’.’ ’N’e’u’r’o’d’y’n’a’m’i’c’ ’t’e’s’t’s’ ’(’f’r’o’m’ ’P’e’t’t’y’ ’&’ ’M’o’o’r’e’ ’2’0’0’1’,’ ’w’i’t’h’ ’p’e’r’m’i’s’s’i’o’n’)’ ’U’p’p’e’r’ ’l’i’m’b’ ’n’e’u’r’o’d’y’n’a’m’i’c’ ’t’e’s’t’s’ ’W’h’e’n’ ’c’o’n’d’u’c’t’i’n’g’ ’t’h’e’ ’u’p’p’e’r’ ’l’i’m’b’ ’n’e’u’r’o’d’y’n’a’m’i’c’ ’t’e’s’t’s’ ’(’U’L’N’T’)’ ’t’h’e’ ’s’e’q’u’e’n’c’e’ ’o’f’ ’ ’t’h’e’ ’t’e’s’t’ ’m’o’v’e’m’e’n’t’s’ ’i’s’ ’r’e’l’a’t’i’v’e’l’y’ ’u’n’i’m’p’o’r’t’a’n’t’ ’a’n’d’ ’m’a’y’ ’b’e’ ’a’d’a’p’t’e’d’ ’t’o’ ’s’u’i’t’ ’t’h’e’ ’p’a’t’i’e’n’t’’’s’ ’c’o’n’d’i’t’i’o’n’.’ ’H’o’w’e’v’e’r’,’ ’i’f’ ’ ’t’h’e’ ’t’e’s’t’s’ ’a’r’e’ ’t’o’ ’b’e’ ’o’f’ ’ ’v’a’l’u’e’ ’a’s’ ’a’n’ ’a’s’s’e’s’s’m’e’n’t’ ’t’o’o’l’,’ ’t’h’e’ ’o’r’d’e’r’ ’u’s’e’d’ ’f’o’r’ ’a’ ’p’a’r’t’i’c’u’l’a’r’ ’p’a’t’i’e’n’t’ ’m’u’s’t’ ’b’e’ ’t’h’e’ ’s’a’m’e’ ’e’a’c’h’ ’t’i’m’e’ ’t’h’e’ ’p’a’t’i’e’n’t’ ’i’s’ ’t’e’s’t’e’d’.’ ’U’L’N’T’ ’1’ ’U’L’N’T’ ’1’ ’(’F’i’g’.’ ’2’.’1’0’)’ ’c’o’n’s’i’s’t’s’ ’o’f’:’ ’●’ ’ ’ ’ ’ ’ ’F’i’x’i’n’g’ ’s’h’o’u’l’d’e’r’ ’t’o’ ’p’r’e’v’e’n’t’ ’s’h’o’u’l’d’e’r’ ’e’l’e’v’a’t’i’o’n’ ’d’u’r’i’n’g’ ’a’b’d’u’c’t’i’o’n’ ’[’1’]’ ’●’ ’ ’ ’ ’ ’ ’S’h’o’u’l’d’e’r’ ’j’o’i’n’t’ ’a’b’d’u’c’t’i’o’n’ ’[’2’]’ ’●’ ’ ’ ’ ’ ’ ’W’r’i’s’t’ ’a’n’d’ ’f’i’n’g’e’r’ ’e’x’t’e’n’s’i’o’n’ ’[’3’]’ ’●’ ’ ’ ’ ’ ’ ’F’o’r’e’a’r’m’ ’s’u’p’i’n’a’t’i’o’n’ ’[’3’]’ ’●’ ’ ’ ’ ’ ’ ’S’h’o’u’l’d’e’r’ ’l’a’t’e’r’a’l’ ’r’o’t’a’t’i’o’n’ ’[’4’]’ ’●’ ’ ’ ’ ’ ’ ’E’l’b’o’w’ ’e’x’t’e’n’s’i’o’n’ ’[’5’]’ ’S’e’n’s’i’t’i’z’i’n’g’ ’t’e’s’t’ ’:’ ’c’e’r’v’i’c’a’l’ ’l’a’t’e’r’a’l’ ’f’l’e’x’i’o’n’ ’a’w’a’y’ ’f’r’o’m’ ’t’h’e’ ’s’y’m’p’-’ ’t’o’m’a’t’i’c’ ’s’i’d’e’ ’[’6’]’.’""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 1 (Median nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of ulnar/median nerve tension and cervical nerve root mobility.""",
    'procedure': r"""Fix shoulder to prevent shoulder elevation during abduction. Shoulder joint abduction. Wrist and finger extension. Forearm supination. Shoulder lateral rotation. Elbow extension.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side (increases symptoms). Desensitizing test: cervical lateral flexion towards the symptomatic side (decreases symptoms).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 2a (Median nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of median nerve tension and shoulder girdle depression.""",
    'procedure': r"""Shoulder girdle depression. Elbow extension. Lateral rotation of whole arm. Wrist, finger and thumb extension. Abduction of shoulder.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side. Desensitizing tests: cervical lateral flexion towards the symptomatic side or release of the shoulder girdle depression.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 2b (Radial nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of radial nerve tension.""",
    'procedure': r"""Shoulder girdle depression. Elbow extension. Medial rotation of whole arm. Wrist and finger flexion. Shoulder abduction.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side. Desensitizing tests: cervical lateral flexion towards the symptomatic side or release of the shoulder girdle depression.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 3 (Ulnar nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of ulnar nerve tension.""",
    'procedure': r"""Shoulder girdle depression. Wrist and finger extension. Forearm pronation. Elbow flexion. Shoulder lateral rotation. Shoulder abduction.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side. Desensitizing tests: cervical lateral flexion towards the symptomatic side or release of the shoulder girdle depression.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Slump test""",
    'category': r"""Neurodynamic""",
    'region': r"""Spine & Lower limb""",
    'purpose': r"""Assessment of neural tension in the spinal cord and lower limbs (sciatic nerve bias).""",
    'procedure': r"""Patient sits upright with knee crease at the edge of plinth and hands behind back. Ask patient to slump spine, flex neck, extend knee, and release neck flexion.""",
    'positive_sign': r"""Reproduction of symptoms. Sensitizing tests: add dorsiflexion or plantarflexion with knee extension; bilateral knee extension; hip abduction.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Straight leg raise (SLR)""",
    'category': r"""Neurodynamic""",
    'region': r"""Lower limb""",
    'purpose': r"""Assessment of dural/sciatic nerve root tension.""",
    'procedure': r"""Passive hip flexion with the knee extended.""",
    'positive_sign': r"""Reproduction of symptoms. Sensitizing tests: dorsiflexion, hip adduction, hip medial rotation, neck flexion, and spinal lateral flexion. Additional: add ankle dorsiflexion and eversion (tibial nerve bias), plantarflexion and inversion (superficial peroneal nerve bias), dorsiflexion and inversion (sural nerve bias).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Slump knee bend""",
    'category': r"""Neurodynamic""",
    'region': r"""Spine & Lower limb""",
    'purpose': r"""Assessment of femoral nerve tension.""",
    'procedure': r"""Patient in side lying. Holds bottom knee to chest and flexes neck. Flex uppermost knee and extend hip.""",
    'positive_sign': r"""Reproduction of symptoms. Desensitizing test: cervical extension.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Finger-nose test""",
    'category': r"""Neurological""",
    'region': r"""Cerebellar""",
    'purpose': r"""Identify possible cerebellar dysfunction (coordination issues).""",
    'procedure': r"""Hold your finger about an arm's length from the patient. Ask the patient to touch your finger with their index finger and then touch their nose, repeating the movement back and forth.""",
    'positive_sign': r"""Patient demonstrates past pointing (missing your finger) or intention tremor.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Heel-shin test""",
    'category': r"""Neurological""",
    'region': r"""Cerebellar""",
    'purpose': r"""Identify possible cerebellar dysfunction in the lower extremities.""",
    'procedure': r"""With the patient lying down, ask them to place one heel on the opposite knee and then run the heel down the tibial shaft towards the ankle and back again.""",
    'positive_sign': r"""Patient demonstrates intention tremor, an inability to keep the heel on the shin, or uncoordinated movements.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Hoffman reflex""",
    'category': r"""Neurological""",
    'region': r"""Reflexes""",
    'purpose': r"""Identify possible upper motor neurone lesion.""",
    'procedure': r"""Flick the distal phalanx of the patient's third or fourth finger. Look for any reflex flexion of the patient's thumb.""",
    'positive_sign': r"""Reflex flexion of the patient's thumb.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Joint position sense""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify loss of proprioception.""",
    'procedure': r"""Test the most distal joint of the limb (e.g. distal phalanx of index finger or hallux). With eyes closed, move joint up/down and ask patient to identify the direction. If impaired, test more proximal joints.""",
    'positive_sign': r"""Inability of the patient to correctly identify the direction of movement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Light touch""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered touch sensation.""",
    'procedure': r"""Use a wisp of cotton wool. With patient's eyes closed, stroke skin at random points, asking them to indicate when they feel the touch.""",
    'positive_sign': r"""Inability to feel the touch or report altered sensation.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Pin prick""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered pain sensation (spinothalamic tract).""",
    'procedure': r"""Use a disposable neurological pin (sharp/blunt). With eyes closed, test various areas randomly and get the patient to identify whether it is sharp or blunt.""",
    'positive_sign': r"""Altered pain sensation or inability to distinguish sharp from blunt.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Plantar reflex (Babinski)""",
    'category': r"""Neurological""",
    'region': r"""Reflexes""",
    'purpose': r"""Identify possible upper motor neurone lesion.""",
    'procedure': r"""Apply firm pressure along the lateral aspect of the sole of the foot and across the base of the toes, observing the big toe.""",
    'positive_sign': r"""The big toe extends and the other toes spread (abnormal response in adults).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Rapidly alternating movement""",
    'category': r"""Neurological""",
    'region': r"""Cerebellar""",
    'purpose': r"""Identify possible cerebellar dysfunction (dysdiadochokinesia).""",
    'procedure': r"""Ask patient to hold out one hand palm up and alternately slap it with palm/dorsum of other hand. For lower limbs, tap feet alternately on floor.""",
    'positive_sign': r"""Loss of rhythm and fluency (dysdiadochokinesia).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Romberg's test""",
    'category': r"""Neurological""",
    'region': r"""Proprioception""",
    'purpose': r"""Differentiate between proprioceptive and vestibular/cerebellar deficit.""",
    'procedure': r"""Patient stands feet together, eyes open, then closes eyes. Observe postural sway or loss of balance.""",
    'positive_sign': r"""Patient loses balance or has excessive postural sway ONLY when eyes are closed (indicates proprioceptive deficit).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Temperature""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered temperature sensation.""",
    'procedure': r"""Apply cold/warm objects (e.g. tuning fork or test tubes filled with water) to various parts of the body, asking the patient to identify the temperature.""",
    'positive_sign': r"""Altered temperature sensation or inability to distinguish hot and cold.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Two-point discrimination""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify impaired sensory function and cortical sensory integrity.""",
    'procedure': r"""Apply two points or one point of a discriminator to the skin with eyes closed. Reduce distance until patient cannot distinguish one from two points. Compare left/right.""",
    'positive_sign': r"""Increased distance threshold (normal is ~5mm in index finger, ~4cm in legs).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Vibration sense""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered vibration sense (posterior columns).""",
    'procedure': r"""Use a 128Hz tuning fork. Apply to bony prominences with eyes closed. Ask patient to identify the vibration and when it stops.""",
    'positive_sign': r"""Altered vibration sense or inability to identify when the vibration stops.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
];
