// Auto-generated file containing pre-parsed tests data from the textbook.
const List<Map<String, String>> initialTestsData = [
  {
    'name': r"""Spurling’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Cervical spine""",
    'purpose': r"""nerve root compression.""",
    'procedure': r"""patient sitting. Extend neck and rotate head. Apply downward pressure to head.""",
    'positive_sign': r"""radiating pain into shoulder or arm on side to which the head is rotated.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Distraction test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Cervical spine""",
    'purpose': r"""nerve root compression.""",
    'procedure': r"""patient in sitting. Place one hand under chin and other hand under occiput. Gently lift patient’s head.""",
    'positive_sign': r"""relief or decrease in pain.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Active compression test (O’Brien)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""labral pathology, acromioclavicular joint pathology.""",
    'procedure': r"""patient upright with elbow in extension and shoul- der in 90° flexion, 10-15° adduction and medial rotation. Stand behind patient and apply downward force to arm. Repeat with arm in lateral rotation.""",
    'positive_sign': r"""pain/increased pain with medial rotation and decreased pain with lateral rotation. Pain inside the gleno- humeral joint indicates labral abnormality. Pain over the acromioclavicular joint indicates acromioclavicular joint abnormality.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Anterior drawer test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""anterior shoulder stability.""",
    'procedure': r"""patient supine. Place shoulder in 80-120° abduc- tion, 0-20° forward flexion and 0-30° lateral rotation. Stabilize scapula. Draw humerus anteriorly.""",
    'positive_sign': r"""click and/or apprehension.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Anterior slide test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""labral pathology.""",
    'procedure': r"""patient upright with hands on hips, thumbs facing posteriorly. Stand behind patient and stabilize scapula and clavicle with one hand. With the other, apply an antero- superior force to elbow while instructing the patient to gently push back against the force.""",
    'positive_sign': r"""pain/reproduction of symptoms/click.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Apprehension test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""glenohumeral joint stability.""",
    'procedure': r"""patient in standing or supine. Abduct shoulder to 90°. Move it into maximum lateral rotation. If movement well tolerated, apply a posteroanterior force to humeral head.""",
    'positive_sign': r"""apprehension and pain.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Biceps load test I""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""superior labral pathology.""",
    'procedure': r"""patient supine with shoulder in 90° abduction, elbow in 90° flexion and forearm supinated. Laterally rotate shoulder until patient becomes apprehensive. Maintain this position. Resist elbow flexion.""",
    'positive_sign': r"""pain/apprehension remains unchanged or increases during resisted elbow flexion.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Biceps load test II""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""superior labral pathology.""",
    'procedure': r"""patient supine with shoulder in 120° abduction and maximum lateral rotation, elbow in 90° flexion and forearm supinated. Resist elbow flexion.""",
    'positive_sign': r"""increased pain during resisted elbow flexion.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Clunk test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""tear of glenoid labrum.""",
    'procedure': r"""patient supine. Abduct shoulder over patient’s head. Apply anterior force to posterior aspect of humeral head while rotating humerus laterally.""",
    'positive_sign': r"""a clunk or grinding sound and/or apprehension if anterior instability present.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Crank test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""labral pathology.""",
    'procedure': r"""patient sitting or supine with shoulder in 160° flexion in scapular plane. Hold elbow and apply a longitu- dinal compressive force to humerus while rotating it medi- ally and laterally.""",
    'positive_sign': r"""pain/reproduction of symptoms, with or with- out click, usually during lateral rotation.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Crossed-arm adduction test (Apley scarf test)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""acromioclavicular joint pathology.""",
    'procedure': r"""patient upright. Horizontally adduct the arm as far as possible.""",
    'positive_sign': r"""pain around acromioclavicular joint.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Drop test (external rotation lag sign)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""infraspinatus and supraspinatus integrity.""",
    'procedure': r"""patient upright with shoulder in 20° abduction (in the scapular plane) with elbow in 90° flexion. Place shoul- der in full lateral rotation. Support elbow and ask patient to hold position.""",
    'positive_sign': r"""arm drops into medial rotation.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Hawkins-Kennedy impingement test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""impingement of supraspinatus tendon.""",
    'procedure': r"""patient sitting or standing. Forward flex shoul- der to 90° and flex elbow to 90°. Apply passive medial rotation.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Hornblower’s sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""teres minor integrity.""",
    'procedure': r"""patient sitting or standing with arms by side. Patient lifts hands up to mouth.""",
    'positive_sign': r"""inability to lift the hand to the mouth without abducting arm first (this compensatory manoeuvre on the affected side is the hornblower’s sign).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Jerk test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""posterior shoulder stability.""",
    'procedure': r"""patient sitting. Place shoulder in 90° forward flex- ion and medial rotation. Apply longitudinal cephalad force to humerus and move arm into horizontal adduction.""",
    'positive_sign': r"""sudden jerk or clunk.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Lift-off test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""subscapularis integrity.""",
    'procedure': r"""patient upright with arm medially rotated behind back. Patient lifts hand away from back.""",
    'positive_sign': r"""inability to lift arm indicates tendon rupture.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Load and shift test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""anterior and posterior shoulder stability.""",
    'procedure': r"""patient sitting. Stabilize scapula by fixing coracoid process and spine of scapula. Grasp humeral head and apply a medial, compressive force to seat it in the glenoid fossa (load). Glide the humeral head anteriorly and poste- riorly (shift).""",
    'positive_sign': r"""increased anterior or posterior glide indicates anterior or posterior instability.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Neer impingement test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""impingement of supraspinatus tendon and/or biceps tendon.""",
    'procedure': r"""patient sitting or standing. Passively elevate arm through forward flexion and medial rotation.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Patte’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""infraspinatus and teres minor integrity.""",
    'procedure': r"""patient sitting. Place shoulder in 90° flexion in the scapular plane and elbow in 90° flexion. Patient rotates arm laterally against resistance.""",
    'positive_sign': r"""resistance with pain indicates tendinopathy. Inability to resist with gradual lowering of the arm or fore- arm indicates tendon rupture.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Posterior drawer test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""posterior shoulder stability.""",
    'procedure': r"""patient supine. Place shoulder in 100-120° abduction and 20-30° forward flexion with elbow flexed to 120°. Stabilize scapula. Medially rotate and forward flex shoulder between 60° and 80° while pushing head of humerus posteriorly.""",
    'positive_sign': r"""significant posterior displacement and/or patient apprehension.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Relocation test (Fowler’s sign)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""differentiates between anterior shoulder stability and primary impingement.""",
    'procedure': r"""perform the apprehension test in supine. At the point where the patient feels pain or apprehension apply an anteroposterior force to humeral head.""",
    'positive_sign': r"""persistence of pain or apprehension indicates primary impingement. Decrease in pain or apprehension and increased lateral rotation indicates instability and sec- ondary impingement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Speed’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""biceps tendon pathology.""",
    'procedure': r"""patient sitting or standing. Forward flex shoul- der, supinate forearm and extend elbow. Resist patient’s attempt to flex shoulder.""",
    'positive_sign': r"""increased pain in bicipital groove.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Sulcus sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""inferior shoulder stability.""",
    'procedure': r"""patient standing or sitting, arm by side. Grip arm below elbow and pull distally.""",
    'positive_sign': r"""reproduction of symptoms and/or appearance of sulcus under acromion.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Supraspinatus (empty can) test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""supraspinatus tendon pathology; suprascapular nerve neuropathy.""",
    'procedure': r"""patient sitting or standing. Abduct shoulder to 90°. Horizontally flex to 30° and medially rotate so thumbs point downwards. Resist patient’s attempt to abduct.""",
    'positive_sign': r"""reproduction of symptoms or weakness.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Yergason’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Shoulder""",
    'purpose': r"""biceps tendon pathology; subacromial impingement.""",
    'procedure': r"""patient sitting or standing with elbow in 90° flex- ion and forearm pronated. Resist patient’s attempts to supinate.""",
    'positive_sign': r"""increased pain in bicipital groove.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Elbow flexion test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""cubital tunnel (ulnar nerve) syndrome.""",
    'procedure': r"""patient standing or sitting. Fully flex elbows with wrist extended. Hold for 5 minutes.""",
    'positive_sign': r"""tingling or paraesthesia in ulnar nerve distribution.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Lateral epicondylitis (tennis elbow) test: method 1""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""lateral epicondylitis.""",
    'procedure': r"""passively extend elbow, pronate forearm and flex wrist and fingers while palpating lateral epicondyle.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Lateral epicondylitis (tennis elbow) test: method 2""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""lateral epicondylitis.""",
    'procedure': r"""resist extension of middle finger distal to PIP (proximal interphalangeal) joint.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Medial epicondylitis (golfer’s elbow) test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""medial epicondylitis.""",
    'procedure': r"""passively extend elbow, supinate forearm and extend wrist and fingers while palpating medial epicondyle.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Pinch grip test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""anterior interosseous (median) nerve entrapment.""",
    'procedure': r"""patient pinches tips of index finger and thumb together.""",
    'positive_sign': r"""inability to pinch tip to tip.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Tinel’s sign (at elbow)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""point of regeneration of sensory fibres of ulnar nerve.""",
    'procedure': r"""tap ulnar nerve in groove between olecranon and medial epicondyle.""",
    'positive_sign': r"""tingling sensation in ulnar distribution of forearm and hand. Furthest point at which abnormal sensation felt indicates point to which the nerve has regenerated.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Valgus stress test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""stability of medial collateral ligament.""",
    'procedure': r"""patient in sitting. Stabilize upper arm with elbow in 20-30° flexion and humerus in full lateral rotation. Apply abduction/valgus force to forearm.""",
    'positive_sign': r"""increased laxity or reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Varus stress test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Elbow""",
    'purpose': r"""stability of lateral collateral ligament.""",
    'procedure': r"""patient in sitting. Stabilize upper arm with elbow in 20-30° flexion and humerus in full medial rotation. Apply adduction/varus force to forearm.""",
    'positive_sign': r"""excessive laxity or reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Finkelstein test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""tenosynovitis of abductor pollicis longus and extensor pollicis brevis tendons (de Quervain’s tenosynovitis).""",
    'procedure': r"""patient makes a fist with thumb inside. Passively move wrist into ulnar deviation.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Froment’s sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""ulnar nerve paralysis.""",
    'procedure': r"""grip piece of paper between index finger and thumb. Pull paper away.""",
    'positive_sign': r"""flexion of IP (interphalangeal) thumb joint as paper pulled away.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Ligamentous instability test for the fingers""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""stability of collateral ligaments.""",
    'procedure': r"""apply valgus and varus force to PIP (proximal interphalangeal) or DIP (distal interphalangeal) joint.""",
    'positive_sign': r"""increased laxity.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Linburg’s sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""tendon pathology at interconnection between flexor pollicis longus and flexor indicis.""",
    'procedure': r"""thumb flexion onto hypothenar eminence and index finger extension.""",
    'positive_sign': r"""limited extension and reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Lunotriquetral ballottement (Reagan’s) test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""stability of lunotriquetral ligament.""",
    'procedure': r"""stabilize lunate and apply posterior and anterior glide to triquetrum and pisiform.""",
    'positive_sign': r"""reproduction of symptoms, crepitus or laxity.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Phalen’s (wrist flexion) test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""median nerve pathology; carpal tunnel syndrome.""",
    'procedure': r"""place dorsal aspect of hands together with wrists flexed. Hold for 1 minute.""",
    'positive_sign': r"""tingling in distribution of median nerve.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Reverse Phalen’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""median nerve pathology.""",
    'procedure': r"""place palms of hands together with wrists extended. Hold for 1 minute.""",
    'positive_sign': r"""tingling in distribution of median nerve.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Sweater finger sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""rupture of flexor digitorum profundus tendon.""",
    'procedure': r"""patient makes a fist.""",
    'positive_sign': r"""loss of DIP joint flexion of one of the fingers.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Tinel’s sign (at the wrist)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""median nerve pathology; carpal tunnel syndrome.""",
    'procedure': r"""tap over carpal tunnel.""",
    'positive_sign': r"""tingling or paraesthesia in median distribution in hand. Furthest point at which abnormal sensation felt indicates point to which the nerve has regenerated.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Triangular fibrocartilage complex (TFCC) load test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""triangular fibrocartilage complex integrity.""",
    'procedure': r"""hold forearm. With other hand hold wrist in ulnar deviation then move it through supination and pronation while applying a compressive force.""",
    'positive_sign': r"""pain, clicking, crepitus.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Watson (scaphoid shift) test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Wrist and hand""",
    'purpose': r"""stability of scaphoid.""",
    'procedure': r"""hold wrist in full ulnar deviation and slight exten- sion. With other hand apply pressure to scaphoid tubercle (palmar aspect) and move wrist into radial deviation and slight flexion.""",
    'positive_sign': r"""pain and/or subluxation of scaphoid.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Compression test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""sprain of posterior sacroiliac joint or ligaments.""",
    'procedure': r"""patient supine or side lying. Push right and left ASIS (anterior superior iliac spine) towards each other.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Gapping test (distraction)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""sprain of anterior sacroiliac joint or ligaments.""",
    'procedure': r"""patient supine. Push right and left ASIS apart.""",
    'positive_sign': r"""reproduction of symptoms.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Femoral shear test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""sacroiliac joint pathology.""",
    'procedure': r"""patient supine with knee flexed and hip in slight flexion, abduction and 45° lateral rotation. Apply a graded longitudinal cephalad force along the femoral axis.""",
    'positive_sign': r"""pain.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Gillet’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""sacroiliac joint dysfunction.""",
    'procedure': r"""patient standing. Palpate PSIS (posterior superior iliac spine) and sacrum at same level. Patient flexes hip and knee on side being palpated while standing on oppo- site leg. Repeat test on other side and compare.""",
    'positive_sign': r"""if the PSIS on the side tested does not move downwards in relation to the sacrum it indicates hypomo- bility on that side.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Piedallu’s sign (sitting flexion)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""movement of sacrum on ilia.""",
    'procedure': r"""patient sitting. Left and right PSIS are palpated while patient forward flexes.""",
    'positive_sign': r"""one side moves higher than the other, indicating hypomobility on that side.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Standing flexion""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""movement of ilia on sacrum.""",
    'procedure': r"""patient standing. Left and right PSIS are palpated while patient forward flexes.""",
    'positive_sign': r"""one side moves higher than the other, indicating hypomobility on that side.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Supine to sit (long sitting) test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Pelvis""",
    'purpose': r"""sacroiliac joint dysfunction caused by pelvic torsion or rotation.""",
    'procedure': r"""patient supine. Note level of inferior borders of medial malleoli. Patient sits up and relative position of malleoli noted.""",
    'positive_sign': r"""one leg moves up more than the other.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Faber’s test (Patrick’s test)""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""hip joint or sacroiliac joint dysfunction; spasm of ilio- psoas muscle.""",
    'procedure': r"""patient supine. Place foot of test leg on opposite knee. Gently lower knee of test leg.""",
    'positive_sign': r"""knee remains above the opposite leg; pain or spasm.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Leg length test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""leg-length discrepancy.""",
    'procedure': r"""patient supine. Measure between the anterior superior iliac spine and the medial or lateral malleolus.""",
    'positive_sign': r"""a difference of more than 1.3 cm is considered significant.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Ober’s sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""tensor fascia lata and iliotibial band contractures.""",
    'procedure': r"""patient in side lying with hip and knee of lower leg flexed. Stabilize pelvis. Passively abduct and extend upper leg with knee extended or flexed to 90°, then allow it to drop towards plinth.""",
    'positive_sign': r"""upper leg remains abducted and does not lower to plinth.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Piriformis test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""piriformis involvement in sciatic pain.""",
    'procedure': r"""patient side lying on edge of bed with test leg uppermost. Flex hip to 60° with knee flexed. Stabilize hip and apply downward pressure to knee.""",
    'positive_sign': r"""localized pain indicates tight piriformis. Pain with radiation indicates sciatic nerve involvement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Quadrant test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""intra-articular hip joint pathology.""",
    'procedure': r"""patient supine. Place hip in full flexion and adduc- tion. Abduct hip in a circular arc, maintaining full flexion, while applying a longitudinal compressive force.""",
    'positive_sign': r"""pain, locking, crepitus, clicking, apprehension.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Rectus femoris contracture test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""rectus femoris contracture.""",
    'procedure': r"""patient supine with test knee flexed to 90° over edge of plinth. Patient hugs other knee to chest.""",
    'positive_sign': r"""knee over edge of plinth extends.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Thomas test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""hip flexion contracture.""",
    'procedure': r"""patient supine. Patient hugs one knee to chest.""",
    'positive_sign': r"""opposite leg lifts off plinth.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Trendelenburg’s sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""stability of the hip, strength of hip abductors (gluteus medius).""",
    'procedure': r"""patient stands on one leg.""",
    'positive_sign': r"""pelvis on opposite side drops.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Weber-Barstow manoeuvre""",
    'category': r"""Musculoskeletal""",
    'region': r"""Hip""",
    'purpose': r"""leg length asymmetry.""",
    'procedure': r"""patient supine with hips and knees flexed. Hold patient’s feet, palpating medial malleoli with thumbs. Patient lifts pelvis off bed and returns to starting position. Passively extend legs and compare relative position of medial malleoli.""",
    'positive_sign': r"""leg length asymmetry.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Abduction (valgus) stress test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""full knee extension: anterior cruciate ligament, medial quadriceps expansion, semimembranosus muscle, medial collateral ligaments, posterior oblique ligament, posterior cruciate ligament, posteromedial capsule. 20-30° flexion: medial collateral ligament, posterior oblique ligament, posterior cruciate ligament, posteromedial capsule.""",
    'procedure': r"""patient supine. Stabilize ankle and apply medial pressure (valgus stress) to knee joint at 0° and then at 20-30° extension.""",
    'positive_sign': r"""excessive movement compared with opposite knee.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Adduction (varus) stress test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""full knee extension: cruciate ligaments, lateral gas- trocnemius muscle, lateral collateral ligament, arcuate- popliteus complex, posterolateral capsule, iliotibial band, biceps femoris tendon. 20-30° flexion: lateral collateral ligament, arcuate- popliteus complex, posterolateral capsule, iliotibial band, biceps fem- oris tendon.""",
    'procedure': r"""patient supine. Stabilize ankle. Apply lateral pres- sure (varus stress) to knee joint at 0° and then at 20-30° extension.""",
    'positive_sign': r"""excessive movement compared to opposite knee.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Anterior drawer test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""anterior cruciate ligament, posterior oblique ligament, arcuate-popliteus complex, posteromedial and posterola- teral capsules, medial collateral ligament, iliotibial band.""",
    'procedure': r"""patient supine with hips flexed to 45° and knee flexed to 90°. Stabilize foot. Apply posteroanterior force to tibia.""",
    'positive_sign': r"""tibia moves more than 6 mm on the femur.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Apley’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""distraction for ligamentous injury; compression for meniscus injury.""",
    'procedure': r"""patient prone with knee flexed to 90°. Medially and laterally rotate tibia - first with distraction and then compression.""",
    'positive_sign': r"""pain.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Brush test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""mild effusion.""",
    'procedure': r"""stroke medial side of patella from just below joint line up to suprapatellar pouch two or three times. Use opposite hand to stroke down lateral side of patella.""",
    'positive_sign': r"""fluid travels to medial side and appears as bulge below distal border of patella.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""External rotation recurvatum test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""posterolateral rotary stability in knee extension.""",
    'procedure': r"""patient supine. Hold heel and place knee in 30° flexion. Slowly extend knee while palpating posterolateral aspect of knee.""",
    'positive_sign': r"""excessive hyperextension and lateral rotation palpated.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Fairbanks ’ apprehension test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""patellar subluxation or dislocation.""",
    'procedure': r"""patient supine with knee in 30° flexion and quads relaxed. Passively glide patella laterally.""",
    'positive_sign': r"""patient apprehension or excessive movement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Hughston plica test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""inflammation of suprapatellar plica.""",
    'procedure': r"""patient supine. Flex and medially rotate knee while applying medial glide to patella and palpating medial fem- oral condyle. Passively extend and flex knee.""",
    'positive_sign': r"""popping of plica band over femoral condyle, tenderness.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Lachman’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""anterior cruciate ligament, posterior oblique ligament, arcuate-popliteus complex.""",
    'procedure': r"""patient supine with knee flexed 0-30°. Stabilize femur. Apply posteroanterior force to tibia.""",
    'positive_sign': r"""soft end feel or excessive movement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""McConnell test for chondromalacia patellae""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""chondromalacia patellae.""",
    'procedure': r"""patient in high sitting with femur laterally rotated. Isometric quad contractions are performed at 0°, 30°, 60°, 90° and 120° of knee flexion for 10 seconds. If pain is produced with any of these movements, repeat test with patella pushed medially.""",
    'positive_sign': r"""decrease in symptoms with medial glide.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""McMurray test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""medial meniscus and lateral meniscus injury.""",
    'procedure': r"""patient supine with test knee completely flexed. To test the medial meniscus, laterally rotate knee and passively extend to 90° while palpating joint line. To test the lateral meniscus, repeat test with the knee in medial rotation.""",
    'positive_sign': r"""a snap or click.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Posterior drawer test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""posterior cruciate ligament, arcuate-popliteus complex, posterior oblique ligament, anterior cruciate ligament.""",
    'procedure': r"""patient supine with hips flexed to 45° and knee flexed to 90°. Stabilize foot. Apply anteroposterior force to tibia.""",
    'positive_sign': r"""excessive movement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Posterior sag sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""posterior cruciate ligament, arcuate-popliteus complex, posterior oblique ligament, anterior cruciate ligament.""",
    'procedure': r"""patient supine with hips flexed to 45° and knee flexed to 90° with feet on plinth.""",
    'positive_sign': r"""tibia drops posteriorly.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Slocum test for anterolateral rotary instability""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""anterior and posterior cruciate ligaments, posterola- teral capsule, arcuate-popliteus complex, lateral collateral ligaments, iliotibial band.""",
    'procedure': r"""patient supine with hips flexed to 45° and knee flexed to 90°. Place foot in 30° medial rotation and stabi- lize. Apply posteroanterior force to tibia.""",
    'positive_sign': r"""excessive movement on lateral side when com- pared with other knee.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Slocum test for anteromedial rotary instability""",
    'category': r"""Musculoskeletal""",
    'region': r"""Knee""",
    'purpose': r"""medial collateral ligament, posterior oblique ligament, posteromedial capsule, anterior cruciate ligament.""",
    'procedure': r"""patient supine with hips flexed to 45° and knee flexed to 90°. Place foot in 15° lateral rotation and stabi- lize. Apply posteroanterior force to tibia.""",
    'positive_sign': r"""excessive movement on medial side when com- pared with other knee.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Anterior drawer sign""",
    'category': r"""Musculoskeletal""",
    'region': r"""Ankle and foot""",
    'purpose': r"""medial and lateral ligament integrity.""",
    'procedure': r"""patient prone with knee flexed. Apply postero- anterior force to talus with ankle in dorsiflexion and then plantarflexion.""",
    'positive_sign': r"""excessive anterior movement (both ligaments affected) or movement on one side only (ligament on that side affected).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Talar tilt""",
    'category': r"""Musculoskeletal""",
    'region': r"""Ankle and foot""",
    'purpose': r"""adduction: mainly integrity of calcaneofibular liga- ment but also anterior talofibular ligament. Abduction: integrity of deltoid ligament.""",
    'procedure': r"""patient prone, supine or side lying with knee flexed. Tilt talus into abduction and adduction with patient’s foot in neutral.""",
    'positive_sign': r"""excessive movement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Thompson’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Ankle and foot""",
    'purpose': r"""Achilles tendon rupture.""",
    'procedure': r"""patient prone with feet over edge of plinth. Squeeze calf muscles.""",
    'positive_sign': r"""absence of plantarflexion.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Adson’s manoeuvre""",
    'category': r"""Musculoskeletal""",
    'region': r"""Common vascular tests""",
    'purpose': r"""thoracic outlet syndrome.""",
    'procedure': r"""patient sitting. Patient turns head towards test arm and extends head. Laterally rotate and extend shoulder and arm while palpating radial pulse. Patient takes a deep breath and holds it.""",
    'positive_sign': r"""disappearance of radial pulse.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Homan’s test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Common vascular tests""",
    'purpose': r"""deep vein thrombophlebitis.""",
    'procedure': r"""patient supine. Passive dorsiflexion of ankle with knee extended.""",
    'positive_sign': r"""pain in the calf.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Provocation elevation test""",
    'category': r"""Musculoskeletal""",
    'region': r"""Common vascular tests""",
    'purpose': r"""thoracic outlet syndrome.""",
    'procedure': r"""patient standing with arms above head. Opens and closes hands 15 times.""",
    'positive_sign': r"""fatigue, cramp, tingling. Neurodynamic tests (from Petty & Moore 2001, with permission) Upper limb neurodynamic tests When conducting the upper limb neurodynamic tests (ULNT) the sequence of the test movements is relatively unimportant and may be adapted to suit the patient’s condition. However, if the tests are to be of value as an assessment tool, the order used for a particular patient must be the same each time the patient is tested. ULNT 1 ULNT 1 (Fig. 2.10) consists of: ● Fixing shoulder to prevent shoulder elevation during abduction [1] ● Shoulder joint abduction [2] ● Wrist and finger extension [3] ● Forearm supination [3] ● Shoulder lateral rotation [4] ● Elbow extension [5] Sensitizing test : cervical lateral flexion away from the symp- tomatic side [6].""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 1 (Median nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of ulnar/median nerve tension and cervical nerve root mobility.""",
    'procedure': r"""Fix shoulder to prevent shoulder elevation during abduction. Shoulder joint abduction. Wrist and finger extension. Forearm supination. Shoulder lateral rotation. Elbow extension.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side (increases symptoms). Desensitizing test: cervical lateral flexion towards the symptomatic side (decreases symptoms).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 2a (Median nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of median nerve tension and shoulder girdle depression.""",
    'procedure': r"""Shoulder girdle depression. Elbow extension. Lateral rotation of whole arm. Wrist, finger and thumb extension. Abduction of shoulder.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side. Desensitizing tests: cervical lateral flexion towards the symptomatic side or release of the shoulder girdle depression.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 2b (Radial nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of radial nerve tension.""",
    'procedure': r"""Shoulder girdle depression. Elbow extension. Medial rotation of whole arm. Wrist and finger flexion. Shoulder abduction.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side. Desensitizing tests: cervical lateral flexion towards the symptomatic side or release of the shoulder girdle depression.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""ULNT 3 (Ulnar nerve bias)""",
    'category': r"""Neurodynamic""",
    'region': r"""Upper limb""",
    'purpose': r"""Assessment of ulnar nerve tension.""",
    'procedure': r"""Shoulder girdle depression. Wrist and finger extension. Forearm pronation. Elbow flexion. Shoulder lateral rotation. Shoulder abduction.""",
    'positive_sign': r"""Reproduction of patient's arm symptoms. Sensitizing test: cervical lateral flexion away from the symptomatic side. Desensitizing tests: cervical lateral flexion towards the symptomatic side or release of the shoulder girdle depression.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Slump test""",
    'category': r"""Neurodynamic""",
    'region': r"""Spine & Lower limb""",
    'purpose': r"""Assessment of neural tension in the spinal cord and lower limbs (sciatic nerve bias).""",
    'procedure': r"""Patient sits upright with knee crease at the edge of plinth and hands behind back. Ask patient to slump spine, flex neck, extend knee, and release neck flexion.""",
    'positive_sign': r"""Reproduction of symptoms. Sensitizing tests: add dorsiflexion or plantarflexion with knee extension; bilateral knee extension; hip abduction.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Straight leg raise (SLR)""",
    'category': r"""Neurodynamic""",
    'region': r"""Lower limb""",
    'purpose': r"""Assessment of dural/sciatic nerve root tension.""",
    'procedure': r"""Passive hip flexion with the knee extended.""",
    'positive_sign': r"""Reproduction of symptoms. Sensitizing tests: dorsiflexion, hip adduction, hip medial rotation, neck flexion, and spinal lateral flexion. Additional: add ankle dorsiflexion and eversion (tibial nerve bias), plantarflexion and inversion (superficial peroneal nerve bias), dorsiflexion and inversion (sural nerve bias).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Slump knee bend""",
    'category': r"""Neurodynamic""",
    'region': r"""Spine & Lower limb""",
    'purpose': r"""Assessment of femoral nerve tension.""",
    'procedure': r"""Patient in side lying. Holds bottom knee to chest and flexes neck. Flex uppermost knee and extend hip.""",
    'positive_sign': r"""Reproduction of symptoms. Desensitizing test: cervical extension.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Finger-nose test""",
    'category': r"""Neurological""",
    'region': r"""Cerebellar""",
    'purpose': r"""Identify possible cerebellar dysfunction (coordination issues).""",
    'procedure': r"""Hold your finger about an arm's length from the patient. Ask the patient to touch your finger with their index finger and then touch their nose, repeating the movement back and forth.""",
    'positive_sign': r"""Patient demonstrates past pointing (missing your finger) or intention tremor.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Heel-shin test""",
    'category': r"""Neurological""",
    'region': r"""Cerebellar""",
    'purpose': r"""Identify possible cerebellar dysfunction in the lower extremities.""",
    'procedure': r"""With the patient lying down, ask them to place one heel on the opposite knee and then run the heel down the tibial shaft towards the ankle and back again.""",
    'positive_sign': r"""Patient demonstrates intention tremor, an inability to keep the heel on the shin, or uncoordinated movements.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Hoffman reflex""",
    'category': r"""Neurological""",
    'region': r"""Reflexes""",
    'purpose': r"""Identify possible upper motor neurone lesion.""",
    'procedure': r"""Flick the distal phalanx of the patient's third or fourth finger. Look for any reflex flexion of the patient's thumb.""",
    'positive_sign': r"""Reflex flexion of the patient's thumb.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Joint position sense""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify loss of proprioception.""",
    'procedure': r"""Test the most distal joint of the limb (e.g. distal phalanx of index finger or hallux). With eyes closed, move joint up/down and ask patient to identify the direction. If impaired, test more proximal joints.""",
    'positive_sign': r"""Inability of the patient to correctly identify the direction of movement.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Light touch""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered touch sensation.""",
    'procedure': r"""Use a wisp of cotton wool. With patient's eyes closed, stroke skin at random points, asking them to indicate when they feel the touch.""",
    'positive_sign': r"""Inability to feel the touch or report altered sensation.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Pin prick""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered pain sensation (spinothalamic tract).""",
    'procedure': r"""Use a disposable neurological pin (sharp/blunt). With eyes closed, test various areas randomly and get the patient to identify whether it is sharp or blunt.""",
    'positive_sign': r"""Altered pain sensation or inability to distinguish sharp from blunt.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Plantar reflex (Babinski)""",
    'category': r"""Neurological""",
    'region': r"""Reflexes""",
    'purpose': r"""Identify possible upper motor neurone lesion.""",
    'procedure': r"""Apply firm pressure along the lateral aspect of the sole of the foot and across the base of the toes, observing the big toe.""",
    'positive_sign': r"""The big toe extends and the other toes spread (abnormal response in adults).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Rapidly alternating movement""",
    'category': r"""Neurological""",
    'region': r"""Cerebellar""",
    'purpose': r"""Identify possible cerebellar dysfunction (dysdiadochokinesia).""",
    'procedure': r"""Ask patient to hold out one hand palm up and alternately slap it with palm/dorsum of other hand. For lower limbs, tap feet alternately on floor.""",
    'positive_sign': r"""Loss of rhythm and fluency (dysdiadochokinesia).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Romberg's test""",
    'category': r"""Neurological""",
    'region': r"""Proprioception""",
    'purpose': r"""Differentiate between proprioceptive and vestibular/cerebellar deficit.""",
    'procedure': r"""Patient stands feet together, eyes open, then closes eyes. Observe postural sway or loss of balance.""",
    'positive_sign': r"""Patient loses balance or has excessive postural sway ONLY when eyes are closed (indicates proprioceptive deficit).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Temperature""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered temperature sensation.""",
    'procedure': r"""Apply cold/warm objects (e.g. tuning fork or test tubes filled with water) to various parts of the body, asking the patient to identify the temperature.""",
    'positive_sign': r"""Altered temperature sensation or inability to distinguish hot and cold.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Two-point discrimination""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify impaired sensory function and cortical sensory integrity.""",
    'procedure': r"""Apply two points or one point of a discriminator to the skin with eyes closed. Reduce distance until patient cannot distinguish one from two points. Compare left/right.""",
    'positive_sign': r"""Increased distance threshold (normal is ~5mm in index finger, ~4cm in legs).""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
  {
    'name': r"""Vibration sense""",
    'category': r"""Neurological""",
    'region': r"""Sensory""",
    'purpose': r"""Identify altered vibration sense (posterior columns).""",
    'procedure': r"""Use a 128Hz tuning fork. Apply to bony prominences with eyes closed. Ask patient to identify the vibration and when it stops.""",
    'positive_sign': r"""Altered vibration sense or inability to identify when the vibration stops.""",
    'patient_position': '',
    'therapist_position': '',
    'interpretation': '',
    'clinical_notes': '',
    'sensitivity': '',
    'specificity': '',
    'important_notes': '',
    'illustration': '',
    'reference': 'The Physiotherapist\'s Pocket Book, Section 2 & 3',
  },
];
